#include "dd/Definitions.hpp"
#include "dd/Export.hpp"
#include "dd/GateMatrixDefinitions.hpp"
#include "dd/LimTable.hpp"
#include "dd/Package.hpp"
#include "dd/QuantumCircuitSimulation.hpp"
#include "dd/QuantumGate.hpp"

#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include <iomanip>
#include <memory>
#include <random>
#include <sstream>

using namespace dd::literals;

// Randomly generated circuit on 3 qubis, containing 30 gates.
TEST(LimTest, randomCliffordCircuit_3) {
    dd::QuantumCircuit circuit(3);

    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Ymat, 0_nc, 1);
    circuit.addGate(dd::Zmat, 2_nc, 1);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Zmat, 1_pc, 0);
    circuit.addGate(dd::Ymat, 1_nc, 0);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Xmat, 2_pc, 0);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Xmat, 2_pc, 0);
    circuit.addGate(dd::Xmat, 2_nc, 1);
    circuit.addGate(dd::Ymat, 1_pc, 0);
    circuit.addGate(dd::Xmat, 2_nc, 0);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Zmat, 2_pc, 1);
    circuit.addGate(dd::Xmat, 0_pc, 1);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Ymat, 1_pc, 0);
    circuit.addGate(dd::Zmat, 2_pc, 1);
    circuit.addGate(dd::Ymat, 1_nc, 0);

    simulateCircuitQMDDvsLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 4 qubis, containing 40 gates.
TEST(LimTest, randomCliffordCircuit_4) {
    dd::QuantumCircuit circuit(4);

    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Xmat, 2_nc, 0);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Ymat, 0_pc, 3);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Xmat, 1_pc, 3);
    circuit.addGate(dd::Zmat, 1_pc, 0);
    circuit.addGate(dd::Xmat, 1_pc, 3);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Ymat, 1_pc, 2);
    circuit.addGate(dd::Ymat, 1_nc, 0);
    circuit.addGate(dd::Zmat, 2_pc, 3);
    circuit.addGate(dd::Ymat, 3_pc, 2);
    circuit.addGate(dd::Xmat, 2_nc, 0);
    circuit.addGate(dd::Zmat, 2_nc, 0);
    circuit.addGate(dd::Zmat, 0_nc, 3);
    circuit.addGate(dd::Xmat, 3_pc, 1);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Xmat, 3_nc, 0);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Ymat, 1_nc, 3);
    circuit.addGate(dd::Ymat, 2_pc, 1);
    circuit.addGate(dd::Ymat, 2_pc, 1);
    circuit.addGate(dd::Zmat, 0_pc, 1);
    circuit.addGate(dd::Zmat, 1_nc, 2);
    circuit.addGate(dd::Xmat, 3_pc, 2);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Zmat, 2_nc, 0);
    circuit.addGate(dd::Zmat, 3_nc, 1);
    circuit.addGate(dd::Zmat, 1_pc, 0);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Ymat, 3_pc, 2);
    circuit.addGate(dd::Xmat, 3_pc, 0);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Xmat, 1);

    simulateCircuitQMDDvsLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 5 qubis, containing 50 gates.
TEST(LimTest, randomCliffordCircuit_5) {
    dd::QuantumCircuit circuit(5);

    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Xmat, 3_pc, 0);
    circuit.addGate(dd::Xmat, 2_nc, 4);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Zmat, 4_nc, 3);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Xmat, 1_nc, 2);
    circuit.addGate(dd::Ymat, 2);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Xmat, 0_pc, 3);
    circuit.addGate(dd::Xmat, 0_nc, 2);
    circuit.addGate(dd::Zmat, 1_pc, 3);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Ymat, 4_nc, 0);
    circuit.addGate(dd::Xmat, 0_pc, 3);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Xmat, 0_nc, 1);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Ymat, 0_pc, 3);
    circuit.addGate(dd::Zmat, 0_nc, 1);
    circuit.addGate(dd::Ymat, 3_nc, 4);
    circuit.addGate(dd::Ymat, 4_pc, 2);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Ymat, 2_nc, 4);
    circuit.addGate(dd::Ymat, 0_pc, 4);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Zmat, 2_nc, 0);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Xmat, 0_pc, 1);
    circuit.addGate(dd::Ymat, 2);
    circuit.addGate(dd::Ymat, 4_pc, 2);
    circuit.addGate(dd::Ymat, 1_pc, 0);
    circuit.addGate(dd::Ymat, 2_nc, 0);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Zmat, 3_nc, 1);
    circuit.addGate(dd::Zmat, 0_nc, 1);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Ymat, 2_nc, 1);
    circuit.addGate(dd::Zmat, 0_nc, 4);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Zmat, 2);

    simulateCircuitQMDDvsLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 6 qubis, containing 60 gates.
TEST(LimTest, randomCliffordCircuit_6) {
    dd::QuantumCircuit circuit(6);

    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Ymat, 3_pc, 2);
    circuit.addGate(dd::Xmat, 1_nc, 2);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Ymat, 3_pc, 4);
    circuit.addGate(dd::Zmat, 5);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Xmat, 4_pc, 3);
    circuit.addGate(dd::Zmat, 4_pc, 1);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Zmat, 5_pc, 1);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Zmat, 5);
    circuit.addGate(dd::Xmat, 0_nc, 5);
    circuit.addGate(dd::Ymat, 4_pc, 5);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Xmat, 4_pc, 1);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Ymat, 2_nc, 1);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Xmat, 3_nc, 0);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Xmat, 1_pc, 2);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Xmat, 3_nc, 5);
    circuit.addGate(dd::Ymat, 2_pc, 4);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Xmat, 5_nc, 0);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Zmat, 5_nc, 3);
    circuit.addGate(dd::Xmat, 1_pc, 4);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Ymat, 0_nc, 1);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Ymat, 2_pc, 1);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Zmat, 5_pc, 3);
    circuit.addGate(dd::Ymat, 4_nc, 2);
    circuit.addGate(dd::Zmat, 1_pc, 0);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Zmat, 4_nc, 5);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Xmat, 0_nc, 3);
    circuit.addGate(dd::Zmat, 2_pc, 0);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Zmat, 3_pc, 5);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Xmat, 2_pc, 3);
    circuit.addGate(dd::Hmat, 2);

    simulateCircuitQMDDvsLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 7 qubis, containing 70 gates.
TEST(LimTest, randomCliffordCircuit_7) {
    dd::QuantumCircuit circuit(7);

    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Zmat, 1_pc, 0);
    circuit.addGate(dd::Zmat, 4_nc, 2);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Xmat, 3_pc, 0);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Zmat, 2_nc, 5);
    circuit.addGate(dd::Zmat, 3_pc, 5);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Zmat, 0_nc, 2);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Zmat, 1_nc, 4);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Ymat, 0_pc, 6);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Ymat, 1_pc, 0);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Zmat, 5_nc, 4);
    circuit.addGate(dd::Zmat, 6);
    circuit.addGate(dd::Ymat, 2_pc, 6);
    circuit.addGate(dd::Ymat, 3_nc, 4);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Xmat, 2_nc, 4);
    circuit.addGate(dd::Ymat, 2_nc, 0);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Ymat, 0_nc, 6);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Ymat, 1_nc, 5);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Ymat, 2_pc, 4);
    circuit.addGate(dd::Ymat, 4_pc, 2);
    circuit.addGate(dd::Xmat, 6_pc, 3);
    circuit.addGate(dd::Zmat, 5_nc, 0);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Ymat, 3_nc, 4);
    circuit.addGate(dd::Ymat, 6_pc, 5);
    circuit.addGate(dd::Xmat, 6_nc, 1);
    circuit.addGate(dd::Xmat, 1_nc, 0);
    circuit.addGate(dd::Ymat, 0_pc, 5);
    circuit.addGate(dd::Ymat, 5_pc, 2);
    circuit.addGate(dd::Zmat, 2_nc, 1);
    circuit.addGate(dd::Zmat, 1_nc, 6);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Zmat, 6_pc, 0);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Xmat, 6_pc, 1);
    circuit.addGate(dd::Xmat, 3_pc, 4);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Xmat, 0_nc, 6);
    circuit.addGate(dd::Zmat, 5_pc, 0);
    circuit.addGate(dd::Ymat, 5_pc, 4);
    circuit.addGate(dd::Zmat, 1_nc, 5);
    circuit.addGate(dd::Zmat, 5_pc, 6);
    circuit.addGate(dd::Smat, 5);

    simulateCircuitQMDDvsLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 8 qubis, containing 80 gates.
TEST(LimTest, randomCliffordCircuit_8) {
    dd::QuantumCircuit circuit(8);

    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Xmat, 3_nc, 1);
    circuit.addGate(dd::Ymat, 0_pc, 5);
    circuit.addGate(dd::Xmat, 0_nc, 1);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Ymat, 0_pc, 4);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Zmat, 3_nc, 4);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Ymat, 6_pc, 0);
    circuit.addGate(dd::Zmat, 6);
    circuit.addGate(dd::Xmat, 7_nc, 3);
    circuit.addGate(dd::Ymat, 6_pc, 0);
    circuit.addGate(dd::Zmat, 0_pc, 2);
    circuit.addGate(dd::Xmat, 5_nc, 2);
    circuit.addGate(dd::Ymat, 1_nc, 2);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Xmat, 6_nc, 5);
    circuit.addGate(dd::Zmat, 6);
    circuit.addGate(dd::Ymat, 7_nc, 2);
    circuit.addGate(dd::Xmat, 3_nc, 2);
    circuit.addGate(dd::Zmat, 0_pc, 7);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Xmat, 7_nc, 6);
    circuit.addGate(dd::Xmat, 3_pc, 6);
    circuit.addGate(dd::Xmat, 1_pc, 7);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Zmat, 2_nc, 3);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Zmat, 5);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Zmat, 6);
    circuit.addGate(dd::Ymat, 3_nc, 5);
    circuit.addGate(dd::Ymat, 7_nc, 3);
    circuit.addGate(dd::Xmat, 6_nc, 7);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Xmat, 0_pc, 2);
    circuit.addGate(dd::Ymat, 6_nc, 5);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Xmat, 7_nc, 2);
    circuit.addGate(dd::Ymat, 5_nc, 3);
    circuit.addGate(dd::Ymat, 5_pc, 1);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Xmat, 1_pc, 5);
    circuit.addGate(dd::Ymat, 4_nc, 0);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Xmat, 6_pc, 7);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Xmat, 4_pc, 3);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Ymat, 0_pc, 6);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Zmat, 0_nc, 1);
    circuit.addGate(dd::Ymat, 2_nc, 6);
    circuit.addGate(dd::Ymat, 1_pc, 4);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Xmat, 1_nc, 3);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Ymat, 3_nc, 7);
    circuit.addGate(dd::Ymat, 0);

    simulateCircuitQMDDvsLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 9 qubis, containing 90 gates.
TEST(LimTest, randomCliffordCircuit_9) {
    dd::QuantumCircuit circuit(9);

    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Zmat, 5);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Ymat, 2_nc, 1);
    circuit.addGate(dd::Zmat, 1_pc, 5);
    circuit.addGate(dd::Ymat, 7);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Ymat, 7_pc, 5);
    circuit.addGate(dd::Ymat, 0_pc, 3);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Xmat, 2_pc, 3);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Xmat, 3_pc, 1);
    circuit.addGate(dd::Ymat, 1_pc, 0);
    circuit.addGate(dd::Ymat, 1_nc, 8);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Ymat, 8_pc, 2);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Zmat, 0_pc, 3);
    circuit.addGate(dd::Ymat, 3_pc, 5);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Ymat, 6_pc, 5);
    circuit.addGate(dd::Ymat, 2_pc, 5);
    circuit.addGate(dd::Xmat, 1_pc, 2);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Ymat, 1_nc, 3);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Ymat, 7_nc, 8);
    circuit.addGate(dd::Ymat, 6_nc, 5);
    circuit.addGate(dd::Zmat, 5_pc, 2);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Xmat, 8_nc, 6);
    circuit.addGate(dd::Ymat, 2_nc, 3);
    circuit.addGate(dd::Zmat, 3_pc, 2);
    circuit.addGate(dd::Ymat, 6_pc, 7);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Ymat, 4_pc, 5);
    circuit.addGate(dd::Zmat, 3_nc, 5);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Zmat, 0_nc, 5);
    circuit.addGate(dd::Xmat, 3_nc, 6);
    circuit.addGate(dd::Xmat, 5_nc, 4);
    circuit.addGate(dd::Zmat, 2_pc, 8);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Zmat, 1_nc, 3);
    circuit.addGate(dd::Xmat, 8_nc, 7);
    circuit.addGate(dd::Ymat, 7);
    circuit.addGate(dd::Xmat, 0_nc, 1);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Ymat, 2);
    circuit.addGate(dd::Zmat, 4_nc, 8);
    circuit.addGate(dd::Ymat, 1_nc, 0);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Ymat, 6_nc, 5);
    circuit.addGate(dd::Xmat, 1_nc, 8);
    circuit.addGate(dd::Zmat, 3_pc, 2);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Ymat, 0_pc, 8);
    circuit.addGate(dd::Xmat, 5_nc, 6);
    circuit.addGate(dd::Xmat, 0_pc, 7);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Xmat, 5_nc, 7);
    circuit.addGate(dd::Xmat, 5_pc, 2);
    circuit.addGate(dd::Zmat, 0_nc, 8);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Xmat, 3_nc, 1);
    circuit.addGate(dd::Zmat, 2_pc, 7);
    circuit.addGate(dd::Ymat, 2_pc, 5);
    circuit.addGate(dd::Ymat, 7_pc, 3);

    simulateCircuitQMDDvsLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 10 qubis, containing 100 gates.
TEST(LimTest, randomCliffordCircuit_10) {
    dd::QuantumCircuit circuit(10);

    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Zmat, 8_nc, 7);
    circuit.addGate(dd::Ymat, 1_pc, 5);
    circuit.addGate(dd::Xmat, 2_nc, 3);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Ymat, 8_pc, 6);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Xmat, 3_nc, 1);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Ymat, 9_pc, 1);
    circuit.addGate(dd::Xmat, 4_nc, 9);
    circuit.addGate(dd::Ymat, 6_pc, 0);
    circuit.addGate(dd::Zmat, 2_pc, 0);
    circuit.addGate(dd::Ymat, 5_nc, 6);
    circuit.addGate(dd::Ymat, 1_pc, 4);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Xmat, 3_nc, 9);
    circuit.addGate(dd::Zmat, 3_pc, 6);
    circuit.addGate(dd::Xmat, 7_nc, 1);
    circuit.addGate(dd::Xmat, 5_pc, 4);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Xmat, 9_pc, 6);
    circuit.addGate(dd::Ymat, 2);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Ymat, 7_nc, 6);
    circuit.addGate(dd::Zmat, 4_pc, 1);
    circuit.addGate(dd::Xmat, 2_pc, 7);
    circuit.addGate(dd::Xmat, 3_pc, 5);
    circuit.addGate(dd::Ymat, 0_nc, 9);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Ymat, 8_pc, 3);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Xmat, 8_pc, 6);
    circuit.addGate(dd::Ymat, 2_nc, 9);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Ymat, 9_nc, 4);
    circuit.addGate(dd::Zmat, 0_pc, 8);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Xmat, 5_nc, 4);
    circuit.addGate(dd::Xmat, 6_pc, 7);
    circuit.addGate(dd::Ymat, 5_nc, 7);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Zmat, 8_pc, 9);
    circuit.addGate(dd::Xmat, 4_nc, 3);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Zmat, 3_nc, 9);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Ymat, 2);
    circuit.addGate(dd::Zmat, 1_nc, 9);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Xmat, 9_nc, 5);
    circuit.addGate(dd::Zmat, 9_pc, 5);
    circuit.addGate(dd::Ymat, 5_nc, 1);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Xmat, 2_pc, 1);
    circuit.addGate(dd::Xmat, 6_pc, 7);
    circuit.addGate(dd::Zmat, 3_pc, 5);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Zmat, 1_nc, 4);
    circuit.addGate(dd::Ymat, 1_nc, 2);
    circuit.addGate(dd::Zmat, 4_nc, 7);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Zmat, 9_pc, 0);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Xmat, 8_nc, 7);
    circuit.addGate(dd::Ymat, 6_nc, 9);
    circuit.addGate(dd::Ymat, 2_nc, 7);
    circuit.addGate(dd::Ymat, 5_nc, 8);
    circuit.addGate(dd::Ymat, 5_pc, 2);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Zmat, 7_pc, 2);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Zmat, 6_pc, 1);
    circuit.addGate(dd::Xmat, 7_nc, 3);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Xmat, 4_nc, 5);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Ymat, 9_nc, 5);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Ymat, 5_nc, 4);
    circuit.addGate(dd::Ymat, 5_pc, 7);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Xmat, 6);

    simulateCircuitQMDDvsLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 11 qubis, containing 110 gates.
TEST(LimTest, randomCliffordCircuit_11) {
    dd::QuantumCircuit circuit(11);

    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Zmat, 9_pc, 5);
    circuit.addGate(dd::Ymat, 1_pc, 8);
    circuit.addGate(dd::Zmat, 7_nc, 1);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Ymat, 3_nc, 5);
    circuit.addGate(dd::Zmat, 1_nc, 3);
    circuit.addGate(dd::Zmat, 4_pc, 5);
    circuit.addGate(dd::Xmat, 0_pc, 4);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Zmat, 9_pc, 8);
    circuit.addGate(dd::Zmat, 6_nc, 10);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Zmat, 1_nc, 3);
    circuit.addGate(dd::Xmat, 0_nc, 8);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Ymat, 7_pc, 6);
    circuit.addGate(dd::Ymat, 10_nc, 0);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Xmat, 8_nc, 9);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Xmat, 4_pc, 7);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Xmat, 5_nc, 9);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Zmat, 3_nc, 5);
    circuit.addGate(dd::Zmat, 7_nc, 6);
    circuit.addGate(dd::Zmat, 9_pc, 8);
    circuit.addGate(dd::Zmat, 2_nc, 10);
    circuit.addGate(dd::Ymat, 7_pc, 4);
    circuit.addGate(dd::Ymat, 6_nc, 7);
    circuit.addGate(dd::Xmat, 3_nc, 7);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Ymat, 10_nc, 9);
    circuit.addGate(dd::Zmat, 10_nc, 0);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Xmat, 5_nc, 4);
    circuit.addGate(dd::Xmat, 4_pc, 2);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Ymat, 7_pc, 9);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Zmat, 0_nc, 9);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Zmat, 10_nc, 5);
    circuit.addGate(dd::Zmat, 5);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Zmat, 9_pc, 8);
    circuit.addGate(dd::Zmat, 0_nc, 3);
    circuit.addGate(dd::Xmat, 9_pc, 5);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Zmat, 7_nc, 2);
    circuit.addGate(dd::Ymat, 9_nc, 2);
    circuit.addGate(dd::Xmat, 9_pc, 10);
    circuit.addGate(dd::Zmat, 1_nc, 5);
    circuit.addGate(dd::Xmat, 9_nc, 5);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Xmat, 10_pc, 1);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Ymat, 10);
    circuit.addGate(dd::Ymat, 2_pc, 0);
    circuit.addGate(dd::Zmat, 2_nc, 1);
    circuit.addGate(dd::Ymat, 2_nc, 1);
    circuit.addGate(dd::Zmat, 6_nc, 10);
    circuit.addGate(dd::Ymat, 2);
    circuit.addGate(dd::Ymat, 8_nc, 6);
    circuit.addGate(dd::Ymat, 6_nc, 10);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Zmat, 7_pc, 10);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Zmat, 5_pc, 9);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Zmat, 9_nc, 6);
    circuit.addGate(dd::Ymat, 2_pc, 8);
    circuit.addGate(dd::Ymat, 9_nc, 7);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Ymat, 5_nc, 6);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Ymat, 1_pc, 2);
    circuit.addGate(dd::Zmat, 6);
    circuit.addGate(dd::Zmat, 0_pc, 3);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Zmat, 1_nc, 5);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Zmat, 1_pc, 10);
    circuit.addGate(dd::Ymat, 0_nc, 2);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Ymat, 4_pc, 7);
    circuit.addGate(dd::Zmat, 3_pc, 0);
    circuit.addGate(dd::Xmat, 8_nc, 4);
    circuit.addGate(dd::Ymat, 2_nc, 6);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Xmat, 0_pc, 6);
    circuit.addGate(dd::Ymat, 1_nc, 10);
    circuit.addGate(dd::Ymat, 0_nc, 2);

    simulateCircuitQMDDvsLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 12 qubis, containing 120 gates.
TEST(LimTest, randomCliffordCircuit_12) {
    dd::QuantumCircuit circuit(12);

    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Xmat, 6_pc, 0);
    circuit.addGate(dd::Ymat, 5_nc, 9);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Xmat, 5_pc, 6);
    circuit.addGate(dd::Zmat, 10_pc, 11);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Ymat, 3_nc, 7);
    circuit.addGate(dd::Xmat, 3_pc, 8);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Zmat, 11_pc, 3);
    circuit.addGate(dd::Ymat, 6_pc, 7);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Xmat, 11_nc, 1);
    circuit.addGate(dd::Ymat, 9_pc, 8);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Xmat, 6_pc, 1);
    circuit.addGate(dd::Xmat, 8_pc, 11);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Smat, 11);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Xmat, 11_nc, 2);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Xmat, 8_pc, 6);
    circuit.addGate(dd::Ymat, 8_nc, 4);
    circuit.addGate(dd::Ymat, 11);
    circuit.addGate(dd::Zmat, 0_pc, 5);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Ymat, 7_pc, 0);
    circuit.addGate(dd::Zmat, 10_pc, 3);
    circuit.addGate(dd::Ymat, 9_pc, 1);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Ymat, 1_nc, 9);
    circuit.addGate(dd::Zmat, 0_nc, 8);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Ymat, 5_pc, 9);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Xmat, 11_pc, 8);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Xmat, 1_pc, 9);
    circuit.addGate(dd::Xmat, 10_pc, 11);
    circuit.addGate(dd::Zmat, 6_nc, 8);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Ymat, 2_nc, 9);
    circuit.addGate(dd::Ymat, 1_pc, 6);
    circuit.addGate(dd::Ymat, 10);
    circuit.addGate(dd::Ymat, 1_nc, 6);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Zmat, 2_pc, 0);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Xmat, 1_pc, 6);
    circuit.addGate(dd::Ymat, 5_nc, 3);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Zmat, 1_pc, 5);
    circuit.addGate(dd::Xmat, 4_nc, 9);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Xmat, 11_nc, 9);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Ymat, 4_pc, 0);
    circuit.addGate(dd::Xmat, 11_nc, 0);
    circuit.addGate(dd::Ymat, 11_nc, 7);
    circuit.addGate(dd::Ymat, 7_pc, 1);
    circuit.addGate(dd::Xmat, 10_nc, 7);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Ymat, 4_pc, 0);
    circuit.addGate(dd::Zmat, 8_nc, 11);
    circuit.addGate(dd::Ymat, 1_nc, 11);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Zmat, 2_pc, 10);
    circuit.addGate(dd::Zmat, 10_nc, 1);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Zmat, 6_pc, 3);
    circuit.addGate(dd::Xmat, 10_pc, 8);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Smat, 11);
    circuit.addGate(dd::Ymat, 2_pc, 0);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Xmat, 5_nc, 2);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Zmat, 5);
    circuit.addGate(dd::Hmat, 7);

    simulateCircuitQMDDvsLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 13 qubis, containing 130 gates.
TEST(LimTest, randomCliffordCircuit_13) {
    dd::QuantumCircuit circuit(13);

    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Zmat, 0_pc, 6);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Ymat, 9_pc, 6);
    circuit.addGate(dd::Zmat, 12);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Zmat, 8_nc, 9);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Ymat, 10_nc, 7);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Zmat, 9_pc, 6);
    circuit.addGate(dd::Xmat, 7_pc, 3);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Xmat, 10_pc, 5);
    circuit.addGate(dd::Ymat, 11_pc, 8);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Xmat, 5_pc, 2);
    circuit.addGate(dd::Xmat, 11_pc, 8);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Xmat, 12_pc, 11);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Zmat, 9_nc, 7);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Ymat, 10_nc, 0);
    circuit.addGate(dd::Smat, 11);
    circuit.addGate(dd::Zmat, 6);
    circuit.addGate(dd::Zmat, 11_pc, 2);
    circuit.addGate(dd::Zmat, 6_pc, 10);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Xmat, 10_pc, 6);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Zmat, 3_nc, 7);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Ymat, 9_pc, 5);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Zmat, 0_nc, 3);
    circuit.addGate(dd::Zmat, 8_nc, 3);
    circuit.addGate(dd::Zmat, 7_pc, 12);
    circuit.addGate(dd::Xmat, 11_nc, 0);
    circuit.addGate(dd::Ymat, 2_nc, 11);
    circuit.addGate(dd::Xmat, 4_nc, 12);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Xmat, 11_nc, 8);
    circuit.addGate(dd::Xmat, 1_nc, 5);
    circuit.addGate(dd::Zmat, 12_nc, 4);
    circuit.addGate(dd::Zmat, 6_nc, 10);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Xmat, 6_nc, 10);
    circuit.addGate(dd::Zmat, 8_pc, 10);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Ymat, 8_pc, 0);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Smat, 11);
    circuit.addGate(dd::Zmat, 10_nc, 8);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Ymat, 7);
    circuit.addGate(dd::Zmat, 6_nc, 10);
    circuit.addGate(dd::Smat, 12);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Xmat, 12_nc, 1);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Xmat, 3_pc, 12);
    circuit.addGate(dd::Ymat, 0_nc, 8);
    circuit.addGate(dd::Ymat, 4_pc, 6);
    circuit.addGate(dd::Zmat, 11_nc, 0);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Zmat, 11_nc, 1);
    circuit.addGate(dd::Ymat, 8_nc, 1);
    circuit.addGate(dd::Xmat, 2_nc, 8);
    circuit.addGate(dd::Zmat, 5_pc, 10);
    circuit.addGate(dd::Ymat, 3_nc, 12);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Zmat, 6_pc, 1);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Ymat, 5_nc, 1);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Xmat, 6_nc, 7);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Xmat, 1_nc, 11);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Ymat, 7_pc, 10);
    circuit.addGate(dd::Xmat, 8_pc, 6);
    circuit.addGate(dd::Xmat, 11_pc, 0);
    circuit.addGate(dd::Ymat, 10_pc, 9);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Zmat, 8_pc, 10);
    circuit.addGate(dd::Ymat, 0_pc, 8);
    circuit.addGate(dd::Zmat, 4_nc, 11);
    circuit.addGate(dd::Zmat, 12_nc, 4);
    circuit.addGate(dd::Xmat, 10_pc, 11);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Xmat, 0_nc, 9);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Zmat, 12_pc, 7);
    circuit.addGate(dd::Ymat, 10);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Xmat, 2_nc, 6);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Xmat, 5_pc, 12);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Smat, 12);
    circuit.addGate(dd::Xmat, 6_nc, 2);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Zmat, 1_pc, 8);
    circuit.addGate(dd::Zmat, 7_nc, 3);
    circuit.addGate(dd::Xmat, 6);

    simulateCircuitQMDDvsLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 14 qubis, containing 140 gates.
TEST(LimTest, randomCliffordCircuit_14) {
    dd::QuantumCircuit circuit(14);

    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Xmat, 6_pc, 0);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Ymat, 13_nc, 6);
    circuit.addGate(dd::Ymat, 6_pc, 5);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Ymat, 1_pc, 10);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Ymat, 9);
    circuit.addGate(dd::Xmat, 10_nc, 1);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Zmat, 5);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Xmat, 12);
    circuit.addGate(dd::Zmat, 4_pc, 1);
    circuit.addGate(dd::Ymat, 7_pc, 12);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Xmat, 8_pc, 9);
    circuit.addGate(dd::Zmat, 13_nc, 7);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Smat, 13);
    circuit.addGate(dd::Smat, 13);
    circuit.addGate(dd::Xmat, 1_nc, 6);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Zmat, 6_pc, 8);
    circuit.addGate(dd::Ymat, 9);
    circuit.addGate(dd::Ymat, 9);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Ymat, 7_pc, 0);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Smat, 12);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Ymat, 11_nc, 8);
    circuit.addGate(dd::Xmat, 13_nc, 4);
    circuit.addGate(dd::Zmat, 1_nc, 2);
    circuit.addGate(dd::Xmat, 4_pc, 1);
    circuit.addGate(dd::Xmat, 10_pc, 1);
    circuit.addGate(dd::Ymat, 2_nc, 13);
    circuit.addGate(dd::Ymat, 11_nc, 13);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Xmat, 1_nc, 2);
    circuit.addGate(dd::Ymat, 10_pc, 0);
    circuit.addGate(dd::Zmat, 12_pc, 11);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Xmat, 0_nc, 6);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Xmat, 2_nc, 0);
    circuit.addGate(dd::Xmat, 10_nc, 0);
    circuit.addGate(dd::Zmat, 12_nc, 13);
    circuit.addGate(dd::Xmat, 6_nc, 4);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Ymat, 10_nc, 3);
    circuit.addGate(dd::Zmat, 5);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Ymat, 9);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Zmat, 1_pc, 11);
    circuit.addGate(dd::Zmat, 7_pc, 11);
    circuit.addGate(dd::Ymat, 3_nc, 9);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Ymat, 10);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Xmat, 12_pc, 9);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Xmat, 4_nc, 0);
    circuit.addGate(dd::Ymat, 11_pc, 7);
    circuit.addGate(dd::Zmat, 8_pc, 9);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Xmat, 12_pc, 0);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Xmat, 0_pc, 1);
    circuit.addGate(dd::Xmat, 3_pc, 7);
    circuit.addGate(dd::Xmat, 8_pc, 6);
    circuit.addGate(dd::Ymat, 5_nc, 9);
    circuit.addGate(dd::Ymat, 11);
    circuit.addGate(dd::Zmat, 9_pc, 7);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Zmat, 13_nc, 11);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Zmat, 3_pc, 7);
    circuit.addGate(dd::Zmat, 4_pc, 6);
    circuit.addGate(dd::Xmat, 13_pc, 6);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Zmat, 12_nc, 0);
    circuit.addGate(dd::Xmat, 5_pc, 11);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Zmat, 5_pc, 6);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Zmat, 12);
    circuit.addGate(dd::Ymat, 2_nc, 10);
    circuit.addGate(dd::Xmat, 5_nc, 4);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Ymat, 3_pc, 11);
    circuit.addGate(dd::Zmat, 3_pc, 6);
    circuit.addGate(dd::Xmat, 4_pc, 12);
    circuit.addGate(dd::Xmat, 12);
    circuit.addGate(dd::Zmat, 12_nc, 10);
    circuit.addGate(dd::Xmat, 4_nc, 2);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Zmat, 9_nc, 10);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Xmat, 2_pc, 7);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Ymat, 11);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Xmat, 8_pc, 0);
    circuit.addGate(dd::Xmat, 1_pc, 11);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Zmat, 12_nc, 3);
    circuit.addGate(dd::Zmat, 8_pc, 2);
    circuit.addGate(dd::Xmat, 6_pc, 4);
    circuit.addGate(dd::Zmat, 13);
    circuit.addGate(dd::Xmat, 5_pc, 6);
    circuit.addGate(dd::Ymat, 10);
    circuit.addGate(dd::Ymat, 11_nc, 0);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Zmat, 2_nc, 9);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Ymat, 1);

    simulateCircuitQMDDvsLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 15 qubis, containing 150 gates.
TEST(LimTest, randomCliffordCircuit_15) {
    dd::QuantumCircuit circuit(15);

    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Ymat, 12_nc, 13);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Xmat, 6_nc, 10);
    circuit.addGate(dd::Ymat, 9_pc, 3);
    circuit.addGate(dd::Zmat, 1_pc, 11);
    circuit.addGate(dd::Ymat, 13);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Zmat, 8_pc, 3);
    circuit.addGate(dd::Xmat, 0_pc, 4);
    circuit.addGate(dd::Ymat, 14);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Zmat, 8_nc, 1);
    circuit.addGate(dd::Zmat, 14_pc, 12);
    circuit.addGate(dd::Ymat, 4_nc, 7);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Zmat, 10_nc, 9);
    circuit.addGate(dd::Xmat, 5_nc, 0);
    circuit.addGate(dd::Zmat, 12);
    circuit.addGate(dd::Zmat, 12);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Ymat, 9);
    circuit.addGate(dd::Ymat, 10_pc, 8);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Ymat, 3_pc, 10);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Xmat, 14_pc, 3);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Xmat, 10_nc, 3);
    circuit.addGate(dd::Xmat, 5_pc, 7);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Xmat, 7_nc, 6);
    circuit.addGate(dd::Zmat, 13_nc, 8);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Ymat, 2_pc, 12);
    circuit.addGate(dd::Ymat, 13);
    circuit.addGate(dd::Ymat, 13_nc, 9);
    circuit.addGate(dd::Ymat, 9);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Zmat, 12_nc, 1);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Ymat, 10_nc, 0);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Ymat, 1_nc, 10);
    circuit.addGate(dd::Zmat, 13_pc, 7);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Zmat, 9_pc, 0);
    circuit.addGate(dd::Zmat, 1_nc, 13);
    circuit.addGate(dd::Xmat, 7_nc, 13);
    circuit.addGate(dd::Zmat, 1_pc, 9);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Zmat, 6_nc, 13);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Xmat, 0_nc, 8);
    circuit.addGate(dd::Ymat, 7_pc, 2);
    circuit.addGate(dd::Xmat, 6_nc, 2);
    circuit.addGate(dd::Xmat, 4_pc, 6);
    circuit.addGate(dd::Ymat, 12_pc, 5);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Hmat, 13);
    circuit.addGate(dd::Zmat, 5_pc, 1);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Xmat, 1_pc, 10);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Ymat, 9);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Ymat, 2);
    circuit.addGate(dd::Ymat, 7_nc, 1);
    circuit.addGate(dd::Xmat, 3_pc, 1);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Zmat, 5_pc, 8);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Xmat, 8_pc, 11);
    circuit.addGate(dd::Smat, 13);
    circuit.addGate(dd::Xmat, 6_pc, 0);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Zmat, 12_pc, 8);
    circuit.addGate(dd::Ymat, 14_pc, 10);
    circuit.addGate(dd::Zmat, 3_pc, 2);
    circuit.addGate(dd::Ymat, 13_pc, 9);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Ymat, 8_nc, 11);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Smat, 12);
    circuit.addGate(dd::Ymat, 9_pc, 10);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Ymat, 3_nc, 7);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Zmat, 0_pc, 11);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Xmat, 14_pc, 4);
    circuit.addGate(dd::Xmat, 6_nc, 11);
    circuit.addGate(dd::Xmat, 3_nc, 7);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Ymat, 12_pc, 8);
    circuit.addGate(dd::Ymat, 5_nc, 1);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Zmat, 5_nc, 4);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Ymat, 7_pc, 11);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Zmat, 13);
    circuit.addGate(dd::Ymat, 13_pc, 1);
    circuit.addGate(dd::Ymat, 8_nc, 9);
    circuit.addGate(dd::Zmat, 8_nc, 1);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Zmat, 6_pc, 2);
    circuit.addGate(dd::Ymat, 6_pc, 1);
    circuit.addGate(dd::Xmat, 7_nc, 10);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Ymat, 5_nc, 14);
    circuit.addGate(dd::Ymat, 0_nc, 7);
    circuit.addGate(dd::Zmat, 6_nc, 12);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Xmat, 4_nc, 8);
    circuit.addGate(dd::Ymat, 2_pc, 8);
    circuit.addGate(dd::Ymat, 9_nc, 14);
    circuit.addGate(dd::Zmat, 14_pc, 10);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Xmat, 7_pc, 14);
    circuit.addGate(dd::Xmat, 13_nc, 4);
    circuit.addGate(dd::Ymat, 13_nc, 9);
    circuit.addGate(dd::Xmat, 1_nc, 8);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Ymat, 2_nc, 13);

    simulateCircuitQMDDvsLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 16 qubis, containing 160 gates.
TEST(LimTest, randomCliffordCircuit_16) {
    dd::QuantumCircuit circuit(16);

    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Hmat, 15);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Ymat, 7);
    circuit.addGate(dd::Ymat, 9_nc, 8);
    circuit.addGate(dd::Xmat, 8_pc, 3);
    circuit.addGate(dd::Ymat, 15);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Zmat, 5_nc, 3);
    circuit.addGate(dd::Zmat, 0_pc, 8);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Zmat, 11_pc, 1);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Xmat, 10_nc, 0);
    circuit.addGate(dd::Zmat, 13);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Ymat, 4_pc, 13);
    circuit.addGate(dd::Zmat, 3_pc, 2);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Zmat, 15);
    circuit.addGate(dd::Zmat, 7_nc, 9);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Ymat, 2_nc, 0);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Zmat, 14_nc, 0);
    circuit.addGate(dd::Ymat, 8_nc, 5);
    circuit.addGate(dd::Xmat, 3_nc, 2);
    circuit.addGate(dd::Ymat, 14_nc, 12);
    circuit.addGate(dd::Ymat, 10_nc, 14);
    circuit.addGate(dd::Hmat, 13);
    circuit.addGate(dd::Zmat, 13);
    circuit.addGate(dd::Zmat, 11_nc, 15);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Xmat, 15_nc, 1);
    circuit.addGate(dd::Ymat, 15);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Xmat, 13);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Xmat, 5_nc, 0);
    circuit.addGate(dd::Zmat, 6_nc, 10);
    circuit.addGate(dd::Smat, 13);
    circuit.addGate(dd::Zmat, 12);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Zmat, 14_nc, 13);
    circuit.addGate(dd::Zmat, 14);
    circuit.addGate(dd::Ymat, 4_nc, 5);
    circuit.addGate(dd::Ymat, 2);
    circuit.addGate(dd::Zmat, 14);
    circuit.addGate(dd::Ymat, 8_pc, 3);
    circuit.addGate(dd::Xmat, 6_pc, 2);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Xmat, 12);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Xmat, 10_nc, 15);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Ymat, 10_pc, 13);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Ymat, 7_pc, 15);
    circuit.addGate(dd::Xmat, 7_nc, 1);
    circuit.addGate(dd::Xmat, 8_pc, 13);
    circuit.addGate(dd::Xmat, 8_nc, 3);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Xmat, 0_pc, 4);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Ymat, 5_pc, 14);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Xmat, 12);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Zmat, 2_nc, 15);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Xmat, 12_nc, 15);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Smat, 14);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Xmat, 10_nc, 15);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Xmat, 6_nc, 5);
    circuit.addGate(dd::Zmat, 9_pc, 6);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Zmat, 9_pc, 6);
    circuit.addGate(dd::Ymat, 0_nc, 3);
    circuit.addGate(dd::Ymat, 8_pc, 7);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Xmat, 15);
    circuit.addGate(dd::Zmat, 6_nc, 8);
    circuit.addGate(dd::Xmat, 7_nc, 8);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Zmat, 13_pc, 1);
    circuit.addGate(dd::Zmat, 10_nc, 5);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Ymat, 10_nc, 14);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Ymat, 10);
    circuit.addGate(dd::Zmat, 9_nc, 13);
    circuit.addGate(dd::Ymat, 2_pc, 1);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Ymat, 14);
    circuit.addGate(dd::Xmat, 10_pc, 13);
    circuit.addGate(dd::Ymat, 13_nc, 2);
    circuit.addGate(dd::Ymat, 0_nc, 15);
    circuit.addGate(dd::Xmat, 1_pc, 9);
    circuit.addGate(dd::Xmat, 13_nc, 0);
    circuit.addGate(dd::Ymat, 6_pc, 12);
    circuit.addGate(dd::Xmat, 1_pc, 4);
    circuit.addGate(dd::Hmat, 15);
    circuit.addGate(dd::Ymat, 3_nc, 4);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Zmat, 11_nc, 6);
    circuit.addGate(dd::Zmat, 12);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Xmat, 13_pc, 0);
    circuit.addGate(dd::Xmat, 5_pc, 15);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Zmat, 7_nc, 11);
    circuit.addGate(dd::Smat, 13);
    circuit.addGate(dd::Xmat, 4_nc, 6);
    circuit.addGate(dd::Zmat, 1_nc, 0);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Xmat, 4_nc, 10);
    circuit.addGate(dd::Xmat, 9_pc, 1);
    circuit.addGate(dd::Zmat, 5_pc, 2);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Zmat, 13);
    circuit.addGate(dd::Zmat, 13_pc, 15);
    circuit.addGate(dd::Ymat, 14_nc, 12);
    circuit.addGate(dd::Xmat, 15_nc, 8);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Xmat, 6_nc, 13);
    circuit.addGate(dd::Xmat, 9_pc, 8);
    circuit.addGate(dd::Ymat, 10_nc, 14);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Hmat, 15);

    simulateCircuitQMDDvsLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 17 qubis, containing 170 gates.
TEST(LimTest, randomCliffordCircuit_17) {
    dd::QuantumCircuit circuit(17);

    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Hmat, 15);
    circuit.addGate(dd::Ymat, 9);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Zmat, 0_pc, 2);
    circuit.addGate(dd::Zmat, 13);
    circuit.addGate(dd::Ymat, 10_nc, 14);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Smat, 14);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Zmat, 0_nc, 11);
    circuit.addGate(dd::Xmat, 9_nc, 13);
    circuit.addGate(dd::Zmat, 10_nc, 2);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Xmat, 6_nc, 11);
    circuit.addGate(dd::Zmat, 7_nc, 5);
    circuit.addGate(dd::Ymat, 15_pc, 9);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Zmat, 12_pc, 6);
    circuit.addGate(dd::Zmat, 4_nc, 8);
    circuit.addGate(dd::Ymat, 8_pc, 13);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Ymat, 13);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Ymat, 16);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Zmat, 14);
    circuit.addGate(dd::Xmat, 8_pc, 3);
    circuit.addGate(dd::Xmat, 13);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Ymat, 9_nc, 4);
    circuit.addGate(dd::Xmat, 2_nc, 15);
    circuit.addGate(dd::Smat, 10);
    circuit.addGate(dd::Zmat, 4_nc, 8);
    circuit.addGate(dd::Zmat, 3_pc, 5);
    circuit.addGate(dd::Xmat, 3_nc, 14);
    circuit.addGate(dd::Xmat, 13_nc, 2);
    circuit.addGate(dd::Xmat, 10_pc, 12);
    circuit.addGate(dd::Xmat, 10_pc, 5);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Ymat, 4_nc, 12);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Zmat, 12_pc, 6);
    circuit.addGate(dd::Xmat, 11_nc, 10);
    circuit.addGate(dd::Ymat, 15);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Zmat, 11_nc, 12);
    circuit.addGate(dd::Ymat, 10);
    circuit.addGate(dd::Ymat, 14);
    circuit.addGate(dd::Zmat, 6);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Ymat, 11);
    circuit.addGate(dd::Xmat, 6_pc, 5);
    circuit.addGate(dd::Ymat, 6_pc, 0);
    circuit.addGate(dd::Xmat, 3_pc, 0);
    circuit.addGate(dd::Zmat, 16);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Xmat, 12);
    circuit.addGate(dd::Xmat, 6_nc, 11);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Zmat, 4_pc, 11);
    circuit.addGate(dd::Xmat, 12);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Xmat, 14_nc, 15);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Xmat, 16_nc, 7);
    circuit.addGate(dd::Ymat, 0_nc, 4);
    circuit.addGate(dd::Zmat, 7_pc, 0);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Smat, 12);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Xmat, 5_pc, 8);
    circuit.addGate(dd::Xmat, 4_nc, 12);
    circuit.addGate(dd::Smat, 14);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Xmat, 10_nc, 5);
    circuit.addGate(dd::Xmat, 9_nc, 7);
    circuit.addGate(dd::Ymat, 7);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Ymat, 2);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Ymat, 11_nc, 14);
    circuit.addGate(dd::Zmat, 12_pc, 1);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Xmat, 9_nc, 3);
    circuit.addGate(dd::Ymat, 12_pc, 5);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Xmat, 8_nc, 11);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Zmat, 16_nc, 4);
    circuit.addGate(dd::Xmat, 2_pc, 3);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Smat, 16);
    circuit.addGate(dd::Xmat, 13_nc, 3);
    circuit.addGate(dd::Ymat, 7);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Ymat, 15);
    circuit.addGate(dd::Ymat, 12_pc, 1);
    circuit.addGate(dd::Xmat, 4_nc, 9);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Smat, 13);
    circuit.addGate(dd::Xmat, 7_nc, 12);
    circuit.addGate(dd::Xmat, 7_nc, 13);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Zmat, 6);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Smat, 16);
    circuit.addGate(dd::Zmat, 16_nc, 3);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Xmat, 15_pc, 8);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Xmat, 11_nc, 8);
    circuit.addGate(dd::Ymat, 9_nc, 15);
    circuit.addGate(dd::Hmat, 16);
    circuit.addGate(dd::Xmat, 3_nc, 16);
    circuit.addGate(dd::Hmat, 15);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Ymat, 6_pc, 8);
    circuit.addGate(dd::Ymat, 0_nc, 2);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Smat, 15);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Zmat, 4_nc, 7);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Zmat, 4_nc, 2);
    circuit.addGate(dd::Xmat, 10_nc, 4);
    circuit.addGate(dd::Xmat, 16);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Ymat, 7_pc, 10);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Xmat, 0_pc, 12);
    circuit.addGate(dd::Zmat, 4_nc, 13);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Xmat, 14_pc, 0);
    circuit.addGate(dd::Ymat, 5_pc, 15);
    circuit.addGate(dd::Zmat, 10_nc, 13);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Xmat, 8_pc, 16);
    circuit.addGate(dd::Zmat, 6_nc, 15);

    simulateCircuitQMDDvsLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 18 qubis, containing 180 gates.
TEST(LimTest, randomCliffordCircuit_18) {
    dd::QuantumCircuit circuit(18);

    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Hmat, 16);
    circuit.addGate(dd::Hmat, 17);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Zmat, 9_pc, 2);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Ymat, 5_nc, 3);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Xmat, 1_nc, 9);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Xmat, 15_pc, 10);
    circuit.addGate(dd::Zmat, 13);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Zmat, 8_nc, 2);
    circuit.addGate(dd::Xmat, 13_pc, 5);
    circuit.addGate(dd::Zmat, 0_pc, 4);
    circuit.addGate(dd::Xmat, 4_nc, 13);
    circuit.addGate(dd::Zmat, 12_nc, 3);
    circuit.addGate(dd::Ymat, 14_nc, 5);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Zmat, 2_pc, 12);
    circuit.addGate(dd::Xmat, 16_nc, 14);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Zmat, 7_pc, 16);
    circuit.addGate(dd::Zmat, 16_pc, 1);
    circuit.addGate(dd::Xmat, 9_pc, 3);
    circuit.addGate(dd::Zmat, 14);
    circuit.addGate(dd::Xmat, 9_pc, 6);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Zmat, 13);
    circuit.addGate(dd::Ymat, 9_nc, 14);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Ymat, 6_pc, 14);
    circuit.addGate(dd::Zmat, 11_pc, 12);
    circuit.addGate(dd::Xmat, 8_pc, 9);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Xmat, 14_pc, 2);
    circuit.addGate(dd::Ymat, 9_pc, 14);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Ymat, 10);
    circuit.addGate(dd::Ymat, 7_nc, 9);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Zmat, 8_nc, 9);
    circuit.addGate(dd::Ymat, 16_pc, 11);
    circuit.addGate(dd::Ymat, 9_pc, 2);
    circuit.addGate(dd::Ymat, 1_pc, 14);
    circuit.addGate(dd::Xmat, 5_nc, 12);
    circuit.addGate(dd::Xmat, 16);
    circuit.addGate(dd::Zmat, 7_nc, 0);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Zmat, 17_nc, 2);
    circuit.addGate(dd::Ymat, 11_nc, 5);
    circuit.addGate(dd::Ymat, 8_nc, 1);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Zmat, 8_pc, 5);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Xmat, 17_nc, 11);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Zmat, 6);
    circuit.addGate(dd::Zmat, 15_pc, 1);
    circuit.addGate(dd::Ymat, 10_nc, 15);
    circuit.addGate(dd::Xmat, 5_pc, 14);
    circuit.addGate(dd::Zmat, 5_pc, 3);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Zmat, 15_nc, 16);
    circuit.addGate(dd::Zmat, 16_nc, 6);
    circuit.addGate(dd::Ymat, 17_pc, 6);
    circuit.addGate(dd::Smat, 17);
    circuit.addGate(dd::Zmat, 2_nc, 9);
    circuit.addGate(dd::Xmat, 10_pc, 15);
    circuit.addGate(dd::Zmat, 16);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Zmat, 6);
    circuit.addGate(dd::Ymat, 12_nc, 1);
    circuit.addGate(dd::Ymat, 5_pc, 0);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Zmat, 12_pc, 10);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Xmat, 10_nc, 11);
    circuit.addGate(dd::Zmat, 9_nc, 15);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Xmat, 0_nc, 2);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Xmat, 5_pc, 14);
    circuit.addGate(dd::Smat, 10);
    circuit.addGate(dd::Xmat, 5_nc, 4);
    circuit.addGate(dd::Zmat, 16);
    circuit.addGate(dd::Xmat, 0_nc, 9);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Zmat, 14);
    circuit.addGate(dd::Xmat, 0_pc, 17);
    circuit.addGate(dd::Zmat, 3_pc, 16);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Ymat, 13);
    circuit.addGate(dd::Hmat, 15);
    circuit.addGate(dd::Ymat, 11);
    circuit.addGate(dd::Ymat, 8_nc, 16);
    circuit.addGate(dd::Ymat, 7);
    circuit.addGate(dd::Xmat, 8_nc, 7);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Ymat, 10);
    circuit.addGate(dd::Zmat, 2_nc, 1);
    circuit.addGate(dd::Xmat, 12_nc, 11);
    circuit.addGate(dd::Xmat, 13);
    circuit.addGate(dd::Ymat, 11_pc, 16);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Xmat, 10_nc, 9);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Ymat, 13_nc, 16);
    circuit.addGate(dd::Hmat, 15);
    circuit.addGate(dd::Hmat, 13);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Zmat, 5);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Ymat, 9_pc, 15);
    circuit.addGate(dd::Ymat, 9_pc, 15);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Ymat, 16);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Xmat, 9_pc, 10);
    circuit.addGate(dd::Hmat, 17);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Xmat, 16_nc, 10);
    circuit.addGate(dd::Zmat, 15);
    circuit.addGate(dd::Ymat, 4_nc, 7);
    circuit.addGate(dd::Zmat, 15);
    circuit.addGate(dd::Zmat, 16_pc, 3);
    circuit.addGate(dd::Ymat, 14_pc, 13);
    circuit.addGate(dd::Ymat, 13_nc, 4);
    circuit.addGate(dd::Ymat, 13);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Zmat, 14_pc, 1);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Ymat, 11);
    circuit.addGate(dd::Ymat, 6_nc, 14);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Xmat, 12_pc, 3);
    circuit.addGate(dd::Zmat, 6_nc, 13);
    circuit.addGate(dd::Ymat, 3_pc, 5);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Zmat, 3_pc, 12);
    circuit.addGate(dd::Zmat, 2_nc, 11);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Ymat, 15_nc, 3);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Xmat, 13_nc, 2);
    circuit.addGate(dd::Ymat, 8_pc, 16);
    circuit.addGate(dd::Xmat, 3_nc, 10);
    circuit.addGate(dd::Hmat, 14);

    simulateCircuitQMDDvsLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 19 qubis, containing 190 gates.
TEST(LimTest, randomCliffordCircuit_19) {
    dd::QuantumCircuit circuit(19);

    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Hmat, 13);
    circuit.addGate(dd::Hmat, 15);
    circuit.addGate(dd::Hmat, 17);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Xmat, 11_nc, 7);
    circuit.addGate(dd::Ymat, 2_pc, 14);
    circuit.addGate(dd::Zmat, 12);
    circuit.addGate(dd::Zmat, 5_pc, 10);
    circuit.addGate(dd::Zmat, 4_nc, 14);
    circuit.addGate(dd::Ymat, 0_pc, 6);
    circuit.addGate(dd::Xmat, 6_nc, 7);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Xmat, 0_pc, 11);
    circuit.addGate(dd::Zmat, 16_nc, 3);
    circuit.addGate(dd::Zmat, 4_pc, 7);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Ymat, 3_pc, 7);
    circuit.addGate(dd::Zmat, 17);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Smat, 17);
    circuit.addGate(dd::Zmat, 15_nc, 4);
    circuit.addGate(dd::Ymat, 3_nc, 11);
    circuit.addGate(dd::Ymat, 3_pc, 16);
    circuit.addGate(dd::Xmat, 2_pc, 4);
    circuit.addGate(dd::Ymat, 17_nc, 12);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Zmat, 0_nc, 8);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Ymat, 14_nc, 11);
    circuit.addGate(dd::Zmat, 18_pc, 2);
    circuit.addGate(dd::Xmat, 0_pc, 13);
    circuit.addGate(dd::Xmat, 12_nc, 10);
    circuit.addGate(dd::Xmat, 9_pc, 4);
    circuit.addGate(dd::Smat, 10);
    circuit.addGate(dd::Zmat, 5_pc, 3);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Xmat, 5_pc, 13);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Xmat, 17_pc, 5);
    circuit.addGate(dd::Xmat, 7_nc, 12);
    circuit.addGate(dd::Zmat, 0_pc, 5);
    circuit.addGate(dd::Zmat, 0_pc, 8);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Ymat, 13_nc, 18);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Xmat, 4_nc, 14);
    circuit.addGate(dd::Xmat, 9_nc, 17);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Zmat, 8_pc, 16);
    circuit.addGate(dd::Zmat, 5_nc, 9);
    circuit.addGate(dd::Ymat, 6_nc, 7);
    circuit.addGate(dd::Xmat, 18);
    circuit.addGate(dd::Xmat, 3_pc, 15);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Zmat, 15_nc, 17);
    circuit.addGate(dd::Xmat, 18);
    circuit.addGate(dd::Ymat, 15_pc, 3);
    circuit.addGate(dd::Smat, 14);
    circuit.addGate(dd::Xmat, 18_pc, 1);
    circuit.addGate(dd::Xmat, 18);
    circuit.addGate(dd::Xmat, 11_nc, 6);
    circuit.addGate(dd::Ymat, 11);
    circuit.addGate(dd::Xmat, 5_pc, 3);
    circuit.addGate(dd::Ymat, 1_nc, 16);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Ymat, 10_nc, 15);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Xmat, 3_pc, 9);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Zmat, 0_pc, 11);
    circuit.addGate(dd::Xmat, 3_nc, 14);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Xmat, 15_pc, 8);
    circuit.addGate(dd::Xmat, 12);
    circuit.addGate(dd::Ymat, 18);
    circuit.addGate(dd::Xmat, 13);
    circuit.addGate(dd::Hmat, 13);
    circuit.addGate(dd::Ymat, 13_nc, 8);
    circuit.addGate(dd::Ymat, 18_pc, 16);
    circuit.addGate(dd::Ymat, 17);
    circuit.addGate(dd::Ymat, 14);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Smat, 14);
    circuit.addGate(dd::Ymat, 13);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Smat, 17);
    circuit.addGate(dd::Xmat, 11_nc, 6);
    circuit.addGate(dd::Ymat, 1_pc, 15);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Zmat, 18);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Xmat, 15);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Ymat, 17_nc, 12);
    circuit.addGate(dd::Zmat, 1_pc, 16);
    circuit.addGate(dd::Ymat, 7);
    circuit.addGate(dd::Xmat, 6_nc, 0);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Zmat, 13_pc, 6);
    circuit.addGate(dd::Ymat, 5_nc, 13);
    circuit.addGate(dd::Xmat, 18_pc, 2);
    circuit.addGate(dd::Smat, 11);
    circuit.addGate(dd::Zmat, 16);
    circuit.addGate(dd::Zmat, 0_nc, 17);
    circuit.addGate(dd::Zmat, 1_pc, 0);
    circuit.addGate(dd::Zmat, 13);
    circuit.addGate(dd::Zmat, 6);
    circuit.addGate(dd::Zmat, 16_pc, 1);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Smat, 15);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Zmat, 10_pc, 1);
    circuit.addGate(dd::Xmat, 1_nc, 15);
    circuit.addGate(dd::Xmat, 1_pc, 2);
    circuit.addGate(dd::Xmat, 9_pc, 0);
    circuit.addGate(dd::Ymat, 10_nc, 14);
    circuit.addGate(dd::Zmat, 18);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Zmat, 0_nc, 18);
    circuit.addGate(dd::Ymat, 2_nc, 14);
    circuit.addGate(dd::Zmat, 5_pc, 7);
    circuit.addGate(dd::Xmat, 11_pc, 13);
    circuit.addGate(dd::Smat, 12);
    circuit.addGate(dd::Xmat, 16);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Zmat, 17);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Xmat, 8_pc, 9);
    circuit.addGate(dd::Xmat, 16_nc, 2);
    circuit.addGate(dd::Xmat, 9_pc, 17);
    circuit.addGate(dd::Hmat, 17);
    circuit.addGate(dd::Ymat, 16);
    circuit.addGate(dd::Smat, 13);
    circuit.addGate(dd::Ymat, 6_nc, 17);
    circuit.addGate(dd::Hmat, 18);
    circuit.addGate(dd::Ymat, 5_nc, 2);
    circuit.addGate(dd::Ymat, 18_pc, 7);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Zmat, 12_nc, 6);
    circuit.addGate(dd::Zmat, 10_pc, 14);
    circuit.addGate(dd::Smat, 16);
    circuit.addGate(dd::Xmat, 0_nc, 4);
    circuit.addGate(dd::Xmat, 10_nc, 12);
    circuit.addGate(dd::Xmat, 8_pc, 18);
    circuit.addGate(dd::Ymat, 8_nc, 9);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Ymat, 16_nc, 15);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Xmat, 16_nc, 9);
    circuit.addGate(dd::Xmat, 12_pc, 0);
    circuit.addGate(dd::Zmat, 13);
    circuit.addGate(dd::Ymat, 14_pc, 9);
    circuit.addGate(dd::Zmat, 5_pc, 16);
    circuit.addGate(dd::Xmat, 3_pc, 12);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Smat, 13);
    circuit.addGate(dd::Smat, 10);
    circuit.addGate(dd::Xmat, 15);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Ymat, 2_nc, 1);
    circuit.addGate(dd::Ymat, 2_nc, 1);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Smat, 13);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Zmat, 16_pc, 3);
    circuit.addGate(dd::Ymat, 18);
    circuit.addGate(dd::Ymat, 2_nc, 6);
    circuit.addGate(dd::Hmat, 17);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Xmat, 0_pc, 13);
    circuit.addGate(dd::Xmat, 17);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Zmat, 2_pc, 6);
    circuit.addGate(dd::Zmat, 11_nc, 3);
    circuit.addGate(dd::Smat, 10);

    simulateCircuitQMDDvsLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 20 qubis, containing 200 gates.
TEST(LimTest, randomCliffordCircuit_20) {
    dd::QuantumCircuit circuit(20);

    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Hmat, 15);
    circuit.addGate(dd::Ymat, 13);
    circuit.addGate(dd::Smat, 10);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Ymat, 10_pc, 7);
    circuit.addGate(dd::Zmat, 6_nc, 7);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Xmat, 15_nc, 9);
    circuit.addGate(dd::Xmat, 10_pc, 3);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Ymat, 16);
    circuit.addGate(dd::Xmat, 18_pc, 13);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Ymat, 13);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Zmat, 6_nc, 18);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Zmat, 3_pc, 16);
    circuit.addGate(dd::Hmat, 13);
    circuit.addGate(dd::Smat, 16);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Xmat, 18_nc, 15);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Zmat, 17_nc, 16);
    circuit.addGate(dd::Xmat, 9_pc, 7);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Zmat, 5);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Ymat, 14);
    circuit.addGate(dd::Zmat, 18);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Zmat, 17_pc, 11);
    circuit.addGate(dd::Xmat, 19);
    circuit.addGate(dd::Xmat, 1_nc, 12);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Ymat, 2);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Ymat, 14_nc, 1);
    circuit.addGate(dd::Ymat, 9);
    circuit.addGate(dd::Smat, 13);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Ymat, 17);
    circuit.addGate(dd::Zmat, 19_pc, 18);
    circuit.addGate(dd::Xmat, 7_pc, 12);
    circuit.addGate(dd::Smat, 19);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Smat, 16);
    circuit.addGate(dd::Xmat, 17);
    circuit.addGate(dd::Zmat, 11_nc, 5);
    circuit.addGate(dd::Zmat, 5);
    circuit.addGate(dd::Zmat, 13);
    circuit.addGate(dd::Ymat, 6_nc, 11);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Xmat, 18_pc, 4);
    circuit.addGate(dd::Xmat, 11_nc, 2);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Xmat, 9_pc, 10);
    circuit.addGate(dd::Ymat, 18);
    circuit.addGate(dd::Ymat, 1_pc, 15);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Smat, 18);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Ymat, 9_pc, 1);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Ymat, 3_pc, 1);
    circuit.addGate(dd::Ymat, 8_pc, 16);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Zmat, 7_nc, 16);
    circuit.addGate(dd::Ymat, 15_pc, 18);
    circuit.addGate(dd::Xmat, 0_nc, 10);
    circuit.addGate(dd::Zmat, 3_nc, 11);
    circuit.addGate(dd::Xmat, 13);
    circuit.addGate(dd::Ymat, 2_pc, 15);
    circuit.addGate(dd::Xmat, 12);
    circuit.addGate(dd::Ymat, 19_pc, 18);
    circuit.addGate(dd::Xmat, 18_pc, 9);
    circuit.addGate(dd::Zmat, 7_pc, 17);
    circuit.addGate(dd::Ymat, 10);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Xmat, 7_nc, 19);
    circuit.addGate(dd::Zmat, 3_nc, 1);
    circuit.addGate(dd::Ymat, 8_nc, 12);
    circuit.addGate(dd::Smat, 13);
    circuit.addGate(dd::Xmat, 3_nc, 16);
    circuit.addGate(dd::Xmat, 13_nc, 3);
    circuit.addGate(dd::Xmat, 5_nc, 1);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Zmat, 4_pc, 12);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Ymat, 15_nc, 16);
    circuit.addGate(dd::Hmat, 18);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Zmat, 19_nc, 5);
    circuit.addGate(dd::Ymat, 19_pc, 16);
    circuit.addGate(dd::Xmat, 15);
    circuit.addGate(dd::Xmat, 19);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Smat, 13);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Hmat, 13);
    circuit.addGate(dd::Zmat, 6_pc, 8);
    circuit.addGate(dd::Ymat, 1_pc, 10);
    circuit.addGate(dd::Xmat, 18_nc, 3);
    circuit.addGate(dd::Zmat, 0_pc, 4);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Hmat, 13);
    circuit.addGate(dd::Ymat, 15_nc, 0);
    circuit.addGate(dd::Smat, 10);
    circuit.addGate(dd::Xmat, 7_pc, 2);
    circuit.addGate(dd::Zmat, 18_pc, 7);
    circuit.addGate(dd::Xmat, 16_nc, 10);
    circuit.addGate(dd::Zmat, 14_nc, 3);
    circuit.addGate(dd::Hmat, 15);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Xmat, 11_nc, 0);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Zmat, 18_pc, 6);
    circuit.addGate(dd::Xmat, 5_pc, 9);
    circuit.addGate(dd::Zmat, 8_pc, 17);
    circuit.addGate(dd::Ymat, 2_nc, 18);
    circuit.addGate(dd::Smat, 16);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Ymat, 11_pc, 18);
    circuit.addGate(dd::Ymat, 2_nc, 19);
    circuit.addGate(dd::Zmat, 5_nc, 2);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Xmat, 19_pc, 5);
    circuit.addGate(dd::Ymat, 5_nc, 13);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Ymat, 14_nc, 5);
    circuit.addGate(dd::Xmat, 14_nc, 13);
    circuit.addGate(dd::Xmat, 15_pc, 7);
    circuit.addGate(dd::Smat, 12);
    circuit.addGate(dd::Xmat, 19);
    circuit.addGate(dd::Zmat, 11_pc, 2);
    circuit.addGate(dd::Xmat, 9_nc, 3);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Ymat, 11_nc, 9);
    circuit.addGate(dd::Zmat, 3_pc, 7);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Zmat, 18_pc, 5);
    circuit.addGate(dd::Zmat, 0_pc, 17);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Zmat, 13_nc, 12);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Zmat, 15);
    circuit.addGate(dd::Ymat, 1_nc, 5);
    circuit.addGate(dd::Xmat, 9_pc, 16);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Xmat, 14_nc, 12);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Zmat, 19);
    circuit.addGate(dd::Ymat, 19);
    circuit.addGate(dd::Xmat, 3_nc, 11);
    circuit.addGate(dd::Zmat, 13_nc, 5);
    circuit.addGate(dd::Ymat, 9);
    circuit.addGate(dd::Hmat, 13);
    circuit.addGate(dd::Zmat, 2_nc, 13);
    circuit.addGate(dd::Xmat, 18);
    circuit.addGate(dd::Zmat, 12_nc, 16);
    circuit.addGate(dd::Zmat, 19);
    circuit.addGate(dd::Xmat, 10_nc, 7);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Smat, 18);
    circuit.addGate(dd::Xmat, 5_nc, 19);
    circuit.addGate(dd::Ymat, 11_pc, 10);

    simulateCircuitQMDDvsLIMDDGateByGate(circuit);
}