// This file contains many quantum circuits that are expected to be hard to simulate using DDs.

#include "dd/Definitions.hpp"
#include "dd/Export.hpp"
#include "dd/GateMatrixDefinitions.hpp"
#include "dd/LimTable.hpp"
#include "dd/Package.hpp"
#include "dd/QuantumCircuitSimulation.hpp"
#include "dd/QuantumGate.hpp"

#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include <iomanip>
#include <memory>
#include <random>
#include <sstream>

using namespace dd::literals;

// Randomly generated circuit on 3 qubis, containing 30 gates.
TEST(LimTest, hardCircuit_3) {
    dd::QuantumCircuit circuit(3);

    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Ymat, 2_pc, 0_nc, 1);
    circuit.addGate(dd::Tdagmat, 1);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Hmat, 1_nc, 2_nc, 0);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Tmat, 1);
    circuit.addGate(dd::Tdagmat, 1);
    circuit.addGate(dd::Tmat, 1);
    circuit.addGate(dd::Tdagmat, 0_nc, 2_pc, 1);
    circuit.addGate(dd::Tdagmat, 2_nc, 0);
    circuit.addGate(dd::Tmat, 2);
    circuit.addGate(dd::Tmat, 1);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Tmat, 2);
    circuit.addGate(dd::Tmat, 0_nc, 1);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Ymat, 2_nc, 0_nc, 1);
    circuit.addGate(dd::Tmat, 2);
    circuit.addGate(dd::Tmat, 2);
    circuit.addGate(dd::Ymat, 1_pc, 2_pc, 0);

    raceCircuitQMDDvsLIMDD(circuit);
}

// Randomly generated circuit on 4 qubis, containing 40 gates.
TEST(LimTest, hardCircuit_4) {
    dd::QuantumCircuit circuit(4);

    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Smat, 1_pc, 0_pc, 2);
    circuit.addGate(dd::Tmat, 0);
    circuit.addGate(dd::Xmat, 1_pc, 2_nc, 0);
    circuit.addGate(dd::Tdagmat, 3);
    circuit.addGate(dd::Smat, 1_nc, 2);
    circuit.addGate(dd::Xmat, 0_pc, 2_pc, 3);
    circuit.addGate(dd::Tmat, 2);
    circuit.addGate(dd::Zmat, 2_pc, 0);
    circuit.addGate(dd::Tmat, 0);
    circuit.addGate(dd::Tmat, 2_pc, 0);
    circuit.addGate(dd::Tdagmat, 0);
    circuit.addGate(dd::Zmat, 1_nc, 2);
    circuit.addGate(dd::Zmat, 0_nc, 1_nc, 3);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Hmat, 3_pc, 2);
    circuit.addGate(dd::Tmat, 0_nc, 2);
    circuit.addGate(dd::Smat, 3_pc, 2_pc, 0);
    circuit.addGate(dd::Ymat, 0_pc, 3);
    circuit.addGate(dd::Tdagmat, 2);
    circuit.addGate(dd::Smat, 0_pc, 2);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Xmat, 1_nc, 2);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Ymat, 2_pc, 3_nc, 0);
    circuit.addGate(dd::Hmat, 0_pc, 1);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Ymat, 1_pc, 0_pc, 2);
    circuit.addGate(dd::Tdagmat, 3);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Hmat, 0_pc, 2_nc, 3);

    raceCircuitQMDDvsLIMDD(circuit);
}

// Randomly generated circuit on 5 qubis, containing 50 gates.
TEST(LimTest, hardCircuit_5) {
    dd::QuantumCircuit circuit(5);

    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Smat, 1_pc, 0);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Ymat, 4_nc, 1);
    circuit.addGate(dd::Ymat, 1_pc, 0_pc, 2);
    circuit.addGate(dd::Tdagmat, 0_nc, 4_pc, 1);
    circuit.addGate(dd::Hmat, 2_pc, 1);
    circuit.addGate(dd::Tdagmat, 1);
    circuit.addGate(dd::Tdagmat, 4);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Tmat, 3_nc, 1_pc, 2);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Tmat, 4);
    circuit.addGate(dd::Smat, 4_pc, 0_nc, 2);
    circuit.addGate(dd::Ymat, 0_nc, 3);
    circuit.addGate(dd::Smat, 2_pc, 4);
    circuit.addGate(dd::Hmat, 2_nc, 1);
    circuit.addGate(dd::Hmat, 0_pc, 2);
    circuit.addGate(dd::Smat, 1_pc, 3_pc, 0);
    circuit.addGate(dd::Hmat, 1_nc, 2_nc, 3);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Tdagmat, 0_pc, 3);
    circuit.addGate(dd::Tdagmat, 0);
    circuit.addGate(dd::Hmat, 3_pc, 1_nc, 0);
    circuit.addGate(dd::Zmat, 2_nc, 4);
    circuit.addGate(dd::Xmat, 1_pc, 2);
    circuit.addGate(dd::Smat, 2_pc, 1_pc, 4);
    circuit.addGate(dd::Xmat, 3_nc, 0_nc, 4);
    circuit.addGate(dd::Ymat, 1_pc, 2);
    circuit.addGate(dd::Tmat, 2_pc, 4_pc, 3);
    circuit.addGate(dd::Hmat, 2_nc, 1_nc, 3);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Smat, 4_nc, 2);
    circuit.addGate(dd::Tmat, 1_pc, 2);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Tdagmat, 2);
    circuit.addGate(dd::Ymat, 1_nc, 2); // triggers an error
    circuit.addGate(dd::Xmat, 2);

    raceCircuitQMDDvsLIMDD(circuit);
}

// Randomly generated circuit on 6 qubis, containing 60 gates.
TEST(LimTest, hardCircuit_6) {
    dd::QuantumCircuit circuit(6);

    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Ymat, 2);
    circuit.addGate(dd::Tdagmat, 5);
    circuit.addGate(dd::Xmat, 5_pc, 1_nc, 0);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Zmat, 1_pc, 3);
    circuit.addGate(dd::Smat, 0_nc, 4);
    circuit.addGate(dd::Tdagmat, 5);
    circuit.addGate(dd::Tdagmat, 3_pc, 4);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Tdagmat, 0_nc, 2);
    circuit.addGate(dd::Xmat, 5_pc, 4_pc, 3);
    circuit.addGate(dd::Tdagmat, 3_nc, 5_pc, 0);
    circuit.addGate(dd::Xmat, 4_nc, 1);
    circuit.addGate(dd::Tdagmat, 3);
    circuit.addGate(dd::Tmat, 5);
    circuit.addGate(dd::Tdagmat, 2);
    circuit.addGate(dd::Smat, 0_nc, 2);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Zmat, 4_nc, 3_nc, 1);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Xmat, 1_pc, 0);
    circuit.addGate(dd::Ymat, 4_pc, 0);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Ymat, 0_nc, 1_pc, 2);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Xmat, 1_pc, 5);
    circuit.addGate(dd::Hmat, 1_pc, 2);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Ymat, 1_nc, 0);
    circuit.addGate(dd::Tdagmat, 3_nc, 2);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Ymat, 3_pc, 5_pc, 0);
    circuit.addGate(dd::Tmat, 2);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Tdagmat, 3_nc, 4_pc, 2);
    circuit.addGate(dd::Tmat, 4_nc, 5);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Tmat, 1_pc, 2);
    circuit.addGate(dd::Zmat, 2_pc, 4_nc, 1);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Hmat, 2_pc, 4_nc, 3);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Ymat, 0_pc, 2_nc, 5);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Tmat, 2);

    raceCircuitQMDDvsLIMDD(circuit);
}

// Randomly generated circuit on 7 qubis, containing 70 gates.
TEST(LimTest, hardCircuit_7) {
    dd::QuantumCircuit circuit(7);

    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Tmat, 3_nc, 5_pc, 4);
    circuit.addGate(dd::Smat, 1_pc, 6);
    circuit.addGate(dd::Ymat, 6_pc, 5);
    circuit.addGate(dd::Tdagmat, 1);
    circuit.addGate(dd::Ymat, 1_pc, 2_pc, 5);
    circuit.addGate(dd::Tmat, 0);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Tdagmat, 2);
    circuit.addGate(dd::Tmat, 5_nc, 1_pc, 4);
    circuit.addGate(dd::Xmat, 1_nc, 3);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Tmat, 5_nc, 6);
    circuit.addGate(dd::Smat, 5_nc, 3);
    circuit.addGate(dd::Tmat, 1_nc, 6_nc, 0);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Xmat, 3_nc, 6);
    circuit.addGate(dd::Tdagmat, 3);
    circuit.addGate(dd::Tmat, 1_nc, 6);
    circuit.addGate(dd::Xmat, 3_pc, 4);
    circuit.addGate(dd::Tdagmat, 5);
    circuit.addGate(dd::Tmat, 3);
    circuit.addGate(dd::Hmat, 2_nc, 6_pc, 4);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Ymat, 4_pc, 1);
    circuit.addGate(dd::Xmat, 6_pc, 0);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Zmat, 5_nc, 0_pc, 6);
    circuit.addGate(dd::Hmat, 3_nc, 2);
    circuit.addGate(dd::Xmat, 2_pc, 3);
    circuit.addGate(dd::Hmat, 6_nc, 1_nc, 2);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Tmat, 5);
    circuit.addGate(dd::Tdagmat, 6);
    circuit.addGate(dd::Ymat, 1_pc, 6);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Tdagmat, 0_nc, 2);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Tmat, 6);
    circuit.addGate(dd::Smat, 3_pc, 5_pc, 6);
    circuit.addGate(dd::Hmat, 0_nc, 3_pc, 5);
    circuit.addGate(dd::Smat, 4_nc, 5_nc, 6);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Zmat, 5_nc, 4_nc, 1);
    circuit.addGate(dd::Xmat, 4_pc, 3_nc, 6);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Zmat, 1_pc, 0);
    circuit.addGate(dd::Tdagmat, 0);
    circuit.addGate(dd::Hmat, 5_pc, 3_nc, 6);
    circuit.addGate(dd::Ymat, 4_nc, 1);
    circuit.addGate(dd::Tmat, 5);
    circuit.addGate(dd::Ymat, 3_pc, 1_nc, 6);
    circuit.addGate(dd::Tmat, 5);
    circuit.addGate(dd::Zmat, 5);
    circuit.addGate(dd::Xmat, 1_nc, 0_nc, 2);
    circuit.addGate(dd::Tdagmat, 3_pc, 0);
    circuit.addGate(dd::Xmat, 5_nc, 1);
    circuit.addGate(dd::Tdagmat, 4_pc, 1_nc, 2);

    raceCircuitQMDDvsLIMDD(circuit);
}

// Randomly generated circuit on 8 qubis, containing 80 gates.
TEST(LimTest, hardCircuit_8) {
    dd::QuantumCircuit circuit(8);

    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Tdagmat, 2_nc, 5);
    circuit.addGate(dd::Tmat, 4);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Smat, 2_pc, 4_pc, 7);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Zmat, 6_nc, 2);
    circuit.addGate(dd::Smat, 5_pc, 7_nc, 2);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Smat, 2_nc, 5);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Smat, 4_nc, 5);
    circuit.addGate(dd::Smat, 2_pc, 0);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Tdagmat, 2_pc, 6);
    circuit.addGate(dd::Ymat, 2_nc, 0_nc, 4);
    circuit.addGate(dd::Zmat, 1_pc, 0_nc, 6);
    circuit.addGate(dd::Tmat, 3);
    circuit.addGate(dd::Xmat, 7_nc, 5_nc, 6);
    circuit.addGate(dd::Ymat, 7_pc, 4_pc, 0);
    circuit.addGate(dd::Tmat, 2_pc, 4_pc, 7);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Tmat, 3);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Ymat, 7_pc, 0);
    circuit.addGate(dd::Tmat, 7);
    circuit.addGate(dd::Xmat, 3_nc, 6);
    circuit.addGate(dd::Hmat, 5_nc, 1);
    circuit.addGate(dd::Zmat, 5);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Ymat, 0_pc, 7_pc, 1);
    circuit.addGate(dd::Tmat, 2_nc, 0_pc, 4);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Smat, 2_pc, 7_pc, 0);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Tdagmat, 1_nc, 6_pc, 3);
    circuit.addGate(dd::Tmat, 7_pc, 3_pc, 4);
    circuit.addGate(dd::Tdagmat, 7_nc, 6);
    circuit.addGate(dd::Zmat, 5_nc, 4_nc, 6);
    circuit.addGate(dd::Ymat, 1_nc, 6_pc, 3);
    circuit.addGate(dd::Tmat, 7);
    circuit.addGate(dd::Tdagmat, 3_nc, 4);
    circuit.addGate(dd::Tdagmat, 3_pc, 2_nc, 1);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Ymat, 5_pc, 4_pc, 3);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Tdagmat, 4);
    circuit.addGate(dd::Zmat, 5_nc, 2);
    circuit.addGate(dd::Xmat, 2_nc, 7);
    circuit.addGate(dd::Tdagmat, 2);
    circuit.addGate(dd::Tmat, 2);
    circuit.addGate(dd::Xmat, 7_pc, 3);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Tdagmat, 1);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Smat, 6_pc, 1_pc, 0);
    circuit.addGate(dd::Hmat, 2_pc, 0_nc, 3);
    circuit.addGate(dd::Zmat, 2_nc, 4_pc, 6);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Hmat, 5_nc, 4);

    raceCircuitQMDDvsLIMDD(circuit);
}

// Randomly generated circuit on 9 qubis, containing 90 gates.
TEST(LimTest, hardCircuit_9) {
    dd::QuantumCircuit circuit(9);

    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Tmat, 4_pc, 7_pc, 8);
    circuit.addGate(dd::Ymat, 8_pc, 1_nc, 7);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Hmat, 2_pc, 8);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Tmat, 3);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Hmat, 5_pc, 4_nc, 6);
    circuit.addGate(dd::Xmat, 2_pc, 3);
    circuit.addGate(dd::Smat, 8_nc, 2);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Smat, 8_pc, 6_pc, 4);
    circuit.addGate(dd::Zmat, 7_pc, 2_nc, 3);
    circuit.addGate(dd::Tdagmat, 2);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Tdagmat, 8_pc, 1_nc, 0);
    circuit.addGate(dd::Ymat, 4_nc, 1);
    circuit.addGate(dd::Tdagmat, 8_pc, 7_pc, 3);
    circuit.addGate(dd::Tdagmat, 3);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Tmat, 3_nc, 5_pc, 6);
    circuit.addGate(dd::Ymat, 4_nc, 2);
    circuit.addGate(dd::Hmat, 0_pc, 3_nc, 4);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Xmat, 1_pc, 0_pc, 3);
    circuit.addGate(dd::Hmat, 1_nc, 4_pc, 7);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Hmat, 1_pc, 3);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Xmat, 8_nc, 4_nc, 5);
    circuit.addGate(dd::Tdagmat, 2_nc, 3_pc, 1);
    circuit.addGate(dd::Hmat, 7_nc, 4);
    circuit.addGate(dd::Tmat, 4_pc, 8);
    circuit.addGate(dd::Smat, 8_nc, 5_pc, 3);
    circuit.addGate(dd::Hmat, 7_pc, 1_pc, 3);
    circuit.addGate(dd::Tmat, 7_pc, 5);
    circuit.addGate(dd::Tdagmat, 5);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Tmat, 6_nc, 8_nc, 7);
    circuit.addGate(dd::Tdagmat, 8);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Xmat, 1_pc, 8_pc, 5);
    circuit.addGate(dd::Tmat, 5);
    circuit.addGate(dd::Tdagmat, 8);
    circuit.addGate(dd::Tdagmat, 1);
    circuit.addGate(dd::Zmat, 3_pc, 6);
    circuit.addGate(dd::Tdagmat, 6);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Tdagmat, 1_nc, 0);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Hmat, 2_pc, 8);
    circuit.addGate(dd::Tmat, 1_pc, 0_nc, 4);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Tmat, 4_nc, 8);
    circuit.addGate(dd::Tmat, 1_pc, 8);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Tdagmat, 3);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Hmat, 2_pc, 1);
    circuit.addGate(dd::Tdagmat, 7);
    circuit.addGate(dd::Smat, 4_nc, 5);
    circuit.addGate(dd::Zmat, 2_pc, 1);
    circuit.addGate(dd::Hmat, 3_pc, 2_nc, 1);
    circuit.addGate(dd::Tdagmat, 2_nc, 8_nc, 7);
    circuit.addGate(dd::Smat, 6_nc, 3);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Tdagmat, 8_nc, 2);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Hmat, 7_pc, 6);
    circuit.addGate(dd::Tmat, 1_nc, 6_nc, 0);
    circuit.addGate(dd::Tdagmat, 2);
    circuit.addGate(dd::Zmat, 5);

    raceCircuitQMDDvsLIMDD(circuit);
}

// Randomly generated circuit on 10 qubis, containing 100 gates.
TEST(LimTest, hardCircuit_10) {
    dd::QuantumCircuit circuit(10);

    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Tdagmat, 5_pc, 2_pc, 7);
    circuit.addGate(dd::Ymat, 8_pc, 7_nc, 0);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Hmat, 7_pc, 9);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Tmat, 0);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Hmat, 1_nc, 5_pc, 4);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Zmat, 3_nc, 7);
    circuit.addGate(dd::Hmat, 8_pc, 3_pc, 4);
    circuit.addGate(dd::Tmat, 8);
    circuit.addGate(dd::Hmat, 3_pc, 5_nc, 2);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Tdagmat, 7);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Tdagmat, 3_pc, 7_nc, 2);
    circuit.addGate(dd::Ymat, 7_pc, 2);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Ymat, 3_pc, 2_nc, 5);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Tmat, 9_nc, 6_nc, 4);
    circuit.addGate(dd::Smat, 2_nc, 7_pc, 0);
    circuit.addGate(dd::Zmat, 0_nc, 7_pc, 3);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Smat, 0_pc, 3);
    circuit.addGate(dd::Ymat, 3_nc, 5_nc, 9);
    circuit.addGate(dd::Tdagmat, 9);
    circuit.addGate(dd::Xmat, 7_nc, 2);
    circuit.addGate(dd::Ymat, 2_pc, 7);
    circuit.addGate(dd::Smat, 1_pc, 8);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Tdagmat, 7_pc, 3_nc, 0);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Xmat, 4_pc, 7_nc, 5);
    circuit.addGate(dd::Zmat, 4_pc, 3);
    circuit.addGate(dd::Smat, 7_pc, 5);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Tdagmat, 9_pc, 2_pc, 3);
    circuit.addGate(dd::Tdagmat, 0);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Tmat, 2_nc, 6_nc, 7);
    circuit.addGate(dd::Xmat, 8_pc, 6);
    circuit.addGate(dd::Tmat, 8_pc, 6_pc, 7);
    circuit.addGate(dd::Tmat, 5);
    circuit.addGate(dd::Tdagmat, 5);
    circuit.addGate(dd::Tdagmat, 2);
    circuit.addGate(dd::Zmat, 2_pc, 3);
    circuit.addGate(dd::Tdagmat, 4);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Tdagmat, 6_nc, 7);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Hmat, 4_pc, 6);
    circuit.addGate(dd::Tmat, 2_pc, 0_nc, 6);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Tmat, 3_nc, 2);
    circuit.addGate(dd::Tmat, 2_pc, 4);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Tdagmat, 5);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 9_pc, 4);
    circuit.addGate(dd::Tdagmat, 6);
    circuit.addGate(dd::Smat, 9_nc, 3);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Tmat, 4);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Tdagmat, 9_nc, 4_nc, 5);
    circuit.addGate(dd::Smat, 4_pc, 1);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 0_nc, 6);
    circuit.addGate(dd::Hmat, 6_nc, 0);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Zmat, 0_pc, 1_pc, 4);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Tmat, 1);
    circuit.addGate(dd::Zmat, 1_pc, 0_pc, 7);
    circuit.addGate(dd::Ymat, 2_pc, 0_nc, 8);
    circuit.addGate(dd::Tmat, 8);
    circuit.addGate(dd::Hmat, 8_nc, 5_nc, 4);

    raceCircuitQMDDvsLIMDD(circuit);
}

// Randomly generated circuit on 11 qubis, containing 110 gates.
TEST(LimTest, hardCircuit_11) {
    dd::QuantumCircuit circuit(11);

    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Tdagmat, 8);
    circuit.addGate(dd::Zmat, 7_pc, 1);
    circuit.addGate(dd::Tmat, 7_nc, 6_pc, 9);
    circuit.addGate(dd::Smat, 10);
    circuit.addGate(dd::Zmat, 8_nc, 5);
    circuit.addGate(dd::Tdagmat, 5);
    circuit.addGate(dd::Xmat, 2_pc, 4_nc, 8);
    circuit.addGate(dd::Tdagmat, 2_nc, 6);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Smat, 1_nc, 10);
    circuit.addGate(dd::Ymat, 7_nc, 8);
    circuit.addGate(dd::Ymat, 6_nc, 4);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Tmat, 7);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Smat, 10);
    circuit.addGate(dd::Ymat, 10_pc, 3_pc, 6);
    circuit.addGate(dd::Tdagmat, 6_nc, 0_pc, 4);
    circuit.addGate(dd::Xmat, 0_pc, 8);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Tmat, 1);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Zmat, 9_pc, 2_nc, 6);
    circuit.addGate(dd::Tdagmat, 1_pc, 5_nc, 6);
    circuit.addGate(dd::Tdagmat, 2_pc, 0);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Xmat, 10_nc, 2);
    circuit.addGate(dd::Tdagmat, 6);
    circuit.addGate(dd::Zmat, 3_pc, 9);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Smat, 10);
    circuit.addGate(dd::Hmat, 1_nc, 8_nc, 9);
    circuit.addGate(dd::Xmat, 10_nc, 0);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Xmat, 9_pc, 7_pc, 0);
    circuit.addGate(dd::Tdagmat, 9);
    circuit.addGate(dd::Tmat, 8);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Zmat, 8_pc, 2);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Tdagmat, 7_pc, 9_nc, 1);
    circuit.addGate(dd::Hmat, 2_pc, 10_nc, 8);
    circuit.addGate(dd::Tmat, 4);
    circuit.addGate(dd::Hmat, 6_nc, 0);
    circuit.addGate(dd::Zmat, 5_pc, 4);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Tmat, 7);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Ymat, 2_pc, 3_nc, 4);
    circuit.addGate(dd::Zmat, 4_nc, 10_pc, 7);
    circuit.addGate(dd::Ymat, 6_pc, 10_nc, 3);
    circuit.addGate(dd::Hmat, 9_pc, 2_pc, 4);
    circuit.addGate(dd::Tmat, 3);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Tmat, 9);
    circuit.addGate(dd::Tdagmat, 3_pc, 5_nc, 4);
    circuit.addGate(dd::Tmat, 0);
    circuit.addGate(dd::Tmat, 0);
    circuit.addGate(dd::Xmat, 0_nc, 4);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Tdagmat, 8);
    circuit.addGate(dd::Hmat, 7_nc, 3_nc, 5);
    circuit.addGate(dd::Xmat, 4_pc, 10_nc, 6);
    circuit.addGate(dd::Zmat, 1_pc, 7);
    circuit.addGate(dd::Xmat, 3_nc, 4_nc, 5);
    circuit.addGate(dd::Xmat, 10_nc, 4_nc, 5);
    circuit.addGate(dd::Ymat, 9);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Tmat, 10_pc, 0_pc, 9);
    circuit.addGate(dd::Tmat, 8);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Xmat, 10_nc, 4);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 1_nc, 10_nc, 2);
    circuit.addGate(dd::Tmat, 1_pc, 9);
    circuit.addGate(dd::Ymat, 7);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Tdagmat, 3);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Smat, 4_pc, 5);
    circuit.addGate(dd::Tdagmat, 6_pc, 0_nc, 7);
    circuit.addGate(dd::Tdagmat, 0);
    circuit.addGate(dd::Smat, 2_nc, 7_pc, 8);
    circuit.addGate(dd::Zmat, 5_nc, 7_pc, 4);
    circuit.addGate(dd::Zmat, 7_nc, 10);
    circuit.addGate(dd::Hmat, 3_pc, 5_nc, 8);
    circuit.addGate(dd::Tmat, 2_nc, 0_nc, 6);
    circuit.addGate(dd::Tdagmat, 9_pc, 0_pc, 1);
    circuit.addGate(dd::Tdagmat, 7);
    circuit.addGate(dd::Xmat, 7);

    raceCircuitQMDDvsLIMDD(circuit);
}

// Randomly generated circuit on 12 qubis, containing 120 gates.
TEST(LimTest, hardCircuit_12) {
    dd::QuantumCircuit circuit(12);

    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Zmat, 9_nc, 4_nc, 10);
    circuit.addGate(dd::Zmat, 5_pc, 0_nc, 4);
    circuit.addGate(dd::Hmat, 2_pc, 6_pc, 7);
    circuit.addGate(dd::Tdagmat, 7);
    circuit.addGate(dd::Zmat, 0_pc, 10);
    circuit.addGate(dd::Xmat, 8_nc, 7_pc, 9);
    circuit.addGate(dd::Ymat, 2);
    circuit.addGate(dd::Ymat, 6_nc, 7);
    circuit.addGate(dd::Tdagmat, 1_pc, 0);
    circuit.addGate(dd::Ymat, 0_pc, 2);
    circuit.addGate(dd::Hmat, 2_nc, 11);
    circuit.addGate(dd::Tmat, 1_pc, 11_nc, 9);
    circuit.addGate(dd::Tdagmat, 1);
    circuit.addGate(dd::Tdagmat, 0_pc, 3);
    circuit.addGate(dd::Smat, 4_pc, 9);
    circuit.addGate(dd::Tdagmat, 0);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Xmat, 11_nc, 7_nc, 0);
    circuit.addGate(dd::Smat, 3_pc, 7);
    circuit.addGate(dd::Xmat, 6_pc, 1_pc, 9);
    circuit.addGate(dd::Ymat, 2_nc, 10);
    circuit.addGate(dd::Zmat, 6_pc, 4_pc, 2);
    circuit.addGate(dd::Tdagmat, 6);
    circuit.addGate(dd::Ymat, 6_nc, 8_pc, 9);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Zmat, 5_nc, 7);
    circuit.addGate(dd::Tmat, 7);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Tmat, 9_nc, 8_pc, 1);
    circuit.addGate(dd::Zmat, 2_pc, 11_nc, 5);
    circuit.addGate(dd::Hmat, 9_nc, 4);
    circuit.addGate(dd::Tdagmat, 9);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Tdagmat, 9_nc, 3);
    circuit.addGate(dd::Tmat, 6);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Tmat, 4_nc, 5);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Tmat, 7_nc, 3);
    circuit.addGate(dd::Zmat, 5_nc, 8);
    circuit.addGate(dd::Ymat, 3_nc, 11);
    circuit.addGate(dd::Ymat, 9_nc, 5);
    circuit.addGate(dd::Xmat, 0_nc, 3_nc, 11);
    circuit.addGate(dd::Xmat, 1_nc, 11_nc, 4);
    circuit.addGate(dd::Tmat, 6_nc, 5_pc, 11);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Smat, 4_pc, 5);
    circuit.addGate(dd::Xmat, 10_nc, 6);
    circuit.addGate(dd::Xmat, 6_pc, 1_nc, 4);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Tdagmat, 1);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Zmat, 10_pc, 11_nc, 4);
    circuit.addGate(dd::Tdagmat, 1_pc, 7_nc, 5);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Tmat, 3);
    circuit.addGate(dd::Tmat, 9);
    circuit.addGate(dd::Smat, 4_nc, 1_nc, 2);
    circuit.addGate(dd::Tdagmat, 10_nc, 2_nc, 9);
    circuit.addGate(dd::Smat, 10_pc, 0);
    circuit.addGate(dd::Tmat, 6_nc, 1_pc, 3);
    circuit.addGate(dd::Ymat, 11_pc, 7);
    circuit.addGate(dd::Zmat, 1_nc, 6_pc, 3);
    circuit.addGate(dd::Tdagmat, 8);
    circuit.addGate(dd::Zmat, 11_pc, 4_nc, 9);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Smat, 2_pc, 0_pc, 3);
    circuit.addGate(dd::Tdagmat, 0_nc, 3);
    circuit.addGate(dd::Tmat, 9_pc, 4);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Tdagmat, 1_nc, 11_pc, 6);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Tdagmat, 8);
    circuit.addGate(dd::Smat, 2_pc, 1_nc, 5);
    circuit.addGate(dd::Smat, 0_pc, 4_pc, 11);
    circuit.addGate(dd::Xmat, 7_pc, 2_nc, 0);
    circuit.addGate(dd::Zmat, 5_nc, 7);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Tmat, 4_pc, 6_pc, 7);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Zmat, 7_pc, 11_nc, 0);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Smat, 11_pc, 5);
    circuit.addGate(dd::Smat, 10);
    circuit.addGate(dd::Zmat, 11_nc, 3_nc, 6);
    circuit.addGate(dd::Tmat, 0_nc, 8);
    circuit.addGate(dd::Tmat, 2_pc, 4);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Hmat, 11_nc, 3_pc, 6);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Xmat, 11_pc, 4);
    circuit.addGate(dd::Zmat, 7_nc, 0_nc, 1);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Ymat, 0_pc, 9);
    circuit.addGate(dd::Ymat, 5_nc, 9);
    circuit.addGate(dd::Tdagmat, 10);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Tdagmat, 10_pc, 5_nc, 6);

    raceCircuitQMDDvsLIMDD(circuit);
}

// Randomly generated circuit on 13 qubis, containing 130 gates.
TEST(LimTest, hardCircuit_13) {
    dd::QuantumCircuit circuit(13);

    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Smat, 12);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Tdagmat, 7_pc, 9);
    circuit.addGate(dd::Xmat, 5_pc, 12);
    circuit.addGate(dd::Hmat, 8_pc, 3_pc, 12);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Hmat, 12_pc, 8);
    circuit.addGate(dd::Tdagmat, 10);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Tmat, 3_pc, 10_nc, 11);
    circuit.addGate(dd::Zmat, 2_nc, 5_nc, 7);
    circuit.addGate(dd::Xmat, 12);
    circuit.addGate(dd::Hmat, 8_nc, 7);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Zmat, 0_nc, 2);
    circuit.addGate(dd::Tmat, 1_pc, 5);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Tdagmat, 7);
    circuit.addGate(dd::Hmat, 5_pc, 3);
    circuit.addGate(dd::Tdagmat, 5);
    circuit.addGate(dd::Ymat, 0_nc, 9_nc, 1);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Ymat, 7_nc, 8);
    circuit.addGate(dd::Zmat, 6);
    circuit.addGate(dd::Smat, 12_pc, 5);
    circuit.addGate(dd::Tdagmat, 9_nc, 0);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Tmat, 7);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Ymat, 5_pc, 12_nc, 8);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Zmat, 7_pc, 12);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Ymat, 3_pc, 8);
    circuit.addGate(dd::Tmat, 8);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Xmat, 9_nc, 4_nc, 8);
    circuit.addGate(dd::Zmat, 0_pc, 11);
    circuit.addGate(dd::Tdagmat, 4);
    circuit.addGate(dd::Xmat, 2_pc, 1_pc, 4);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Tmat, 5_pc, 12);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Tdagmat, 0_pc, 11);
    circuit.addGate(dd::Zmat, 11_nc, 12_pc, 6);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Xmat, 0_nc, 5_nc, 9);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Hmat, 7_nc, 6);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Smat, 12_pc, 3_pc, 0);
    circuit.addGate(dd::Tdagmat, 3);
    circuit.addGate(dd::Zmat, 4_pc, 0);
    circuit.addGate(dd::Hmat, 1_nc, 8_pc, 5);
    circuit.addGate(dd::Tdagmat, 12_pc, 10);
    circuit.addGate(dd::Tmat, 12);
    circuit.addGate(dd::Xmat, 1_nc, 0);
    circuit.addGate(dd::Ymat, 9);
    circuit.addGate(dd::Xmat, 7_nc, 0_pc, 11);
    circuit.addGate(dd::Xmat, 5_nc, 9);
    circuit.addGate(dd::Zmat, 3_pc, 10_pc, 7);
    circuit.addGate(dd::Ymat, 7);
    circuit.addGate(dd::Zmat, 1_nc, 8_nc, 2);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Ymat, 0_pc, 11_nc, 2);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Hmat, 12_nc, 1_nc, 10);
    circuit.addGate(dd::Smat, 9_nc, 12_nc, 0);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Hmat, 7_nc, 1);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Ymat, 12_nc, 4_pc, 2);
    circuit.addGate(dd::Xmat, 6_pc, 1_nc, 4);
    circuit.addGate(dd::Tdagmat, 11_nc, 5);
    circuit.addGate(dd::Tmat, 9);
    circuit.addGate(dd::Smat, 10);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Tdagmat, 5_pc, 1);
    circuit.addGate(dd::Ymat, 2_nc, 0);
    circuit.addGate(dd::Xmat, 4_nc, 3);
    circuit.addGate(dd::Zmat, 5);
    circuit.addGate(dd::Tdagmat, 11_nc, 5_pc, 1);
    circuit.addGate(dd::Ymat, 11_pc, 0_nc, 6);
    circuit.addGate(dd::Tdagmat, 12);
    circuit.addGate(dd::Smat, 10);
    circuit.addGate(dd::Ymat, 7);
    circuit.addGate(dd::Tdagmat, 12);
    circuit.addGate(dd::Ymat, 7_pc, 12_pc, 6);
    circuit.addGate(dd::Xmat, 12);
    circuit.addGate(dd::Ymat, 6_nc, 11_nc, 5);
    circuit.addGate(dd::Tmat, 11_nc, 12_nc, 1);
    circuit.addGate(dd::Xmat, 12);
    circuit.addGate(dd::Ymat, 7_nc, 0);
    circuit.addGate(dd::Xmat, 5_nc, 12);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Tdagmat, 9_nc, 7_pc, 4);
    circuit.addGate(dd::Ymat, 11);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Tdagmat, 12);
    circuit.addGate(dd::Zmat, 6_pc, 5);
    circuit.addGate(dd::Tmat, 2);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Smat, 10);
    circuit.addGate(dd::Tdagmat, 5_nc, 7);
    circuit.addGate(dd::Tdagmat, 1_pc, 5_nc, 4);
    circuit.addGate(dd::Tdagmat, 2);
    circuit.addGate(dd::Zmat, 8_pc, 0_nc, 3);
    circuit.addGate(dd::Tdagmat, 9_nc, 5_nc, 10);
    circuit.addGate(dd::Ymat, 1_nc, 7_nc, 10);
    circuit.addGate(dd::Tmat, 5_nc, 2);
    circuit.addGate(dd::Smat, 12_nc, 8);

    raceCircuitQMDDvsLIMDD(circuit);
}

// Randomly generated circuit on 14 qubis, containing 140 gates.
TEST(LimTest, hardCircuit_14) {
    dd::QuantumCircuit circuit(14);

    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Tdagmat, 9_pc, 13);
    circuit.addGate(dd::Xmat, 13);
    circuit.addGate(dd::Ymat, 11_pc, 7_nc, 5);
    circuit.addGate(dd::Tmat, 2_nc, 7_nc, 3);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Hmat, 9_pc, 13);
    circuit.addGate(dd::Tmat, 13_nc, 8);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Tmat, 13);
    circuit.addGate(dd::Tdagmat, 6_pc, 0);
    circuit.addGate(dd::Tdagmat, 4_pc, 13);
    circuit.addGate(dd::Tmat, 8);
    circuit.addGate(dd::Zmat, 3_pc, 13_pc, 6);
    circuit.addGate(dd::Tdagmat, 9_nc, 13_nc, 7);
    circuit.addGate(dd::Tdagmat, 9_nc, 5_nc, 3);
    circuit.addGate(dd::Ymat, 3_pc, 1_nc, 11);
    circuit.addGate(dd::Xmat, 12_nc, 13);
    circuit.addGate(dd::Smat, 13_pc, 11_nc, 5);
    circuit.addGate(dd::Xmat, 5_nc, 4_pc, 10);
    circuit.addGate(dd::Tmat, 9);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Zmat, 13_pc, 4);
    circuit.addGate(dd::Hmat, 9_nc, 8_nc, 4);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Zmat, 9_nc, 5_nc, 6);
    circuit.addGate(dd::Smat, 5_nc, 3_pc, 12);
    circuit.addGate(dd::Smat, 3_nc, 10_pc, 4);
    circuit.addGate(dd::Smat, 11);
    circuit.addGate(dd::Smat, 11);
    circuit.addGate(dd::Zmat, 13);
    circuit.addGate(dd::Smat, 7_nc, 4_pc, 5);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Hmat, 12_nc, 6_pc, 10);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Hmat, 1_pc, 4);
    circuit.addGate(dd::Ymat, 3_nc, 13_pc, 0);
    circuit.addGate(dd::Smat, 10);
    circuit.addGate(dd::Tdagmat, 7_nc, 12);
    circuit.addGate(dd::Xmat, 2_pc, 3);
    circuit.addGate(dd::Hmat, 4_pc, 6);
    circuit.addGate(dd::Hmat, 0_nc, 7_nc, 3);
    circuit.addGate(dd::Xmat, 5_pc, 1);
    circuit.addGate(dd::Tdagmat, 0);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Zmat, 8_pc, 1_pc, 6);
    circuit.addGate(dd::Tmat, 6_pc, 10_pc, 2);
    circuit.addGate(dd::Hmat, 1_pc, 0);
    circuit.addGate(dd::Zmat, 1_pc, 12);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Hmat, 8_nc, 2);
    circuit.addGate(dd::Ymat, 8_nc, 13);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Tdagmat, 12_pc, 10);
    circuit.addGate(dd::Smat, 12);
    circuit.addGate(dd::Zmat, 1_pc, 12);
    circuit.addGate(dd::Tdagmat, 11);
    circuit.addGate(dd::Smat, 10_nc, 3);
    circuit.addGate(dd::Tdagmat, 4_pc, 13_nc, 8);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Tdagmat, 10_pc, 7);
    circuit.addGate(dd::Ymat, 13_nc, 3);
    circuit.addGate(dd::Hmat, 2_pc, 4_nc, 3);
    circuit.addGate(dd::Smat, 7_nc, 3);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Tmat, 9_pc, 1);
    circuit.addGate(dd::Tdagmat, 7_nc, 13);
    circuit.addGate(dd::Zmat, 0_nc, 8_nc, 11);
    circuit.addGate(dd::Zmat, 9_nc, 5);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Xmat, 9_pc, 3);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Smat, 8_nc, 10_pc, 6);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Xmat, 3_pc, 0_pc, 1);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Xmat, 2_pc, 10);
    circuit.addGate(dd::Tdagmat, 0_pc, 11_nc, 8);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 4_pc, 3);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Tmat, 7);
    circuit.addGate(dd::Tmat, 9_nc, 8);
    circuit.addGate(dd::Tmat, 7);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Tmat, 13);
    circuit.addGate(dd::Tdagmat, 3);
    circuit.addGate(dd::Tmat, 1);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Hmat, 2_pc, 10_nc, 3);
    circuit.addGate(dd::Tmat, 13_nc, 5);
    circuit.addGate(dd::Xmat, 6_nc, 1_nc, 8);
    circuit.addGate(dd::Hmat, 10_pc, 9_pc, 7);
    circuit.addGate(dd::Tdagmat, 2);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Smat, 8_pc, 4_nc, 5);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Ymat, 0_pc, 4);
    circuit.addGate(dd::Xmat, 3_pc, 12_nc, 13);
    circuit.addGate(dd::Zmat, 13_nc, 3_pc, 4);
    circuit.addGate(dd::Tmat, 1_pc, 9_nc, 11);
    circuit.addGate(dd::Tmat, 13);
    circuit.addGate(dd::Tdagmat, 13);
    circuit.addGate(dd::Tmat, 0_pc, 12_pc, 6);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Smat, 13_pc, 4_nc, 12);
    circuit.addGate(dd::Tmat, 4);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Tmat, 11_nc, 1_nc, 13);
    circuit.addGate(dd::Zmat, 11_nc, 8_pc, 12);
    circuit.addGate(dd::Tmat, 4);
    circuit.addGate(dd::Xmat, 12);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Xmat, 7_nc, 10);
    circuit.addGate(dd::Ymat, 4_nc, 5);

    raceCircuitQMDDvsLIMDD(circuit);
}

// Randomly generated circuit on 15 qubis, containing 150 gates.
TEST(LimTest, hardCircuit_15) {
    dd::QuantumCircuit circuit(15);

    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Hmat, 13);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Tdagmat, 14_nc, 12);
    circuit.addGate(dd::Tdagmat, 0_pc, 14_pc, 9);
    circuit.addGate(dd::Zmat, 3_nc, 8_nc, 11);
    circuit.addGate(dd::Tmat, 0_nc, 4_pc, 8);
    circuit.addGate(dd::Tmat, 12_pc, 14_nc, 10);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Tmat, 6);
    circuit.addGate(dd::Tmat, 12_nc, 9);
    circuit.addGate(dd::Ymat, 1_nc, 8);
    circuit.addGate(dd::Ymat, 9);
    circuit.addGate(dd::Xmat, 1_pc, 5);
    circuit.addGate(dd::Tmat, 7);
    circuit.addGate(dd::Xmat, 2_pc, 9);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Ymat, 1_pc, 5_pc, 14);
    circuit.addGate(dd::Tmat, 4);
    circuit.addGate(dd::Ymat, 12_pc, 6_nc, 8);
    circuit.addGate(dd::Tdagmat, 8_nc, 14);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Xmat, 0_nc, 3_pc, 1);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Tmat, 8);
    circuit.addGate(dd::Hmat, 12_nc, 1_pc, 8);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Tmat, 8_pc, 12);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Hmat, 10_pc, 12_pc, 1);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Tmat, 14_pc, 1);
    circuit.addGate(dd::Tmat, 12_nc, 6_nc, 13);
    circuit.addGate(dd::Xmat, 13);
    circuit.addGate(dd::Smat, 14);
    circuit.addGate(dd::Tmat, 11_pc, 13_nc, 1);
    circuit.addGate(dd::Zmat, 14);
    circuit.addGate(dd::Tmat, 6_pc, 10_nc, 7);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Tdagmat, 13);
    circuit.addGate(dd::Tdagmat, 12);
    circuit.addGate(dd::Xmat, 12_nc, 11);
    circuit.addGate(dd::Hmat, 9_pc, 2_pc, 1);
    circuit.addGate(dd::Smat, 12);
    circuit.addGate(dd::Tdagmat, 7_nc, 12_nc, 11);
    circuit.addGate(dd::Hmat, 9_nc, 0_nc, 4);
    circuit.addGate(dd::Tdagmat, 9_nc, 1);
    circuit.addGate(dd::Zmat, 9_nc, 3);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Tmat, 5_nc, 12_nc, 6);
    circuit.addGate(dd::Zmat, 4_pc, 5_pc, 10);
    circuit.addGate(dd::Tmat, 4);
    circuit.addGate(dd::Tdagmat, 13);
    circuit.addGate(dd::Zmat, 2_pc, 8);
    circuit.addGate(dd::Xmat, 10_pc, 12);
    circuit.addGate(dd::Zmat, 13_pc, 0);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Tmat, 6_nc, 9);
    circuit.addGate(dd::Tdagmat, 5_pc, 14_nc, 11);
    circuit.addGate(dd::Hmat, 6_nc, 11);
    circuit.addGate(dd::Ymat, 3_nc, 13);
    circuit.addGate(dd::Tdagmat, 7);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Tdagmat, 10);
    circuit.addGate(dd::Tdagmat, 5);
    circuit.addGate(dd::Tmat, 11);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Smat, 0_pc, 4);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Zmat, 13);
    circuit.addGate(dd::Ymat, 4_nc, 3_nc, 0);
    circuit.addGate(dd::Ymat, 14);
    circuit.addGate(dd::Xmat, 13);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Tdagmat, 10);
    circuit.addGate(dd::Tdagmat, 5_pc, 3_nc, 8);
    circuit.addGate(dd::Ymat, 1_nc, 11_pc, 13);
    circuit.addGate(dd::Tdagmat, 12_pc, 7_pc, 13);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Ymat, 13_nc, 10);
    circuit.addGate(dd::Tmat, 1);
    circuit.addGate(dd::Xmat, 8_pc, 2_nc, 14);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Zmat, 5);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Ymat, 5_nc, 4_nc, 12);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Xmat, 3_nc, 11);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Ymat, 9_nc, 10);
    circuit.addGate(dd::Smat, 5_pc, 12_nc, 0);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Smat, 11_nc, 14);
    circuit.addGate(dd::Smat, 6_nc, 14_nc, 3);
    circuit.addGate(dd::Smat, 9_pc, 10_nc, 6);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Tdagmat, 12_nc, 6);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Smat, 2_pc, 11);
    circuit.addGate(dd::Zmat, 6_nc, 1_pc, 3);
    circuit.addGate(dd::Xmat, 11_nc, 5);
    circuit.addGate(dd::Zmat, 7_pc, 2);
    circuit.addGate(dd::Xmat, 5_pc, 9);
    circuit.addGate(dd::Hmat, 9_nc, 6_nc, 12);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Smat, 0_pc, 1);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Smat, 5_pc, 8);
    circuit.addGate(dd::Tmat, 9);
    circuit.addGate(dd::Tmat, 3_pc, 12_nc, 9);
    circuit.addGate(dd::Tmat, 6);
    circuit.addGate(dd::Tmat, 7);
    circuit.addGate(dd::Tmat, 5);
    circuit.addGate(dd::Smat, 14);
    circuit.addGate(dd::Ymat, 9_pc, 11);
    circuit.addGate(dd::Tdagmat, 10_pc, 14);
    circuit.addGate(dd::Tdagmat, 0_nc, 11);
    circuit.addGate(dd::Zmat, 8_pc, 14);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Smat, 13_pc, 11);
    circuit.addGate(dd::Hmat, 11_pc, 7_nc, 9);
    circuit.addGate(dd::Smat, 4_pc, 13);
    circuit.addGate(dd::Ymat, 9_nc, 4);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Hmat, 5_nc, 4_pc, 10);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Smat, 14);
    circuit.addGate(dd::Tdagmat, 4);
    circuit.addGate(dd::Tdagmat, 6);
    circuit.addGate(dd::Tdagmat, 9_pc, 8);

    raceCircuitQMDDvsLIMDD(circuit);
}