#include "dd/Definitions.hpp"
#include "dd/Export.hpp"
#include "dd/GateMatrixDefinitions.hpp"
#include "dd/Package.hpp"
#include "dd/QuantumCircuitSimulation.hpp"

#include "gtest/gtest.h"
#include <memory>

using namespace dd::literals;

// Randomly generated circuit on 10 qubis, containing 30 Clifford gates.
TEST(LimTest, generatedCircuit_1) {
    dd::QuantumCircuit circuit(10);

    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Xmat, 3_pc, 2);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Zmat, 2_pc, 0);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Xmat, 4_pc, 3);
    circuit.addGate(dd::Xmat, 2_pc, 9);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Zmat, 2_pc, 8);
    circuit.addGate(dd::Ymat, 0_pc, 4);
    circuit.addGate(dd::Zmat, 4_pc, 9);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Zmat, 5_pc, 6);
    circuit.addGate(dd::Zmat, 6);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Zmat, 7_pc, 6);
    circuit.addGate(dd::Ymat, 4_pc, 6);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Zmat, 5_pc, 3);
    circuit.addGate(dd::Zmat, 5);
    circuit.addGate(dd::Ymat, 1_pc, 8);
    circuit.addGate(dd::Ymat, 6_pc, 0);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Ymat, 8_pc, 0);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Hmat, 9);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 11 qubis, containing 33 Clifford gates.
TEST(LimTest, generatedCircuit_2) {
    dd::QuantumCircuit circuit(11);

    circuit.addGate(dd::Xmat, 10_pc, 4);
    circuit.addGate(dd::Zmat, 7_pc, 5);
    circuit.addGate(dd::Xmat, 3_pc, 2);
    circuit.addGate(dd::Zmat, 3_pc, 5);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Xmat, 3_pc, 8);
    circuit.addGate(dd::Zmat, 8_pc, 9);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Ymat, 6_pc, 4);
    circuit.addGate(dd::Xmat, 10_pc, 6);
    circuit.addGate(dd::Zmat, 7_pc, 0);
    circuit.addGate(dd::Zmat, 2_pc, 1);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Ymat, 7_pc, 0);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Ymat, 6_pc, 1);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Xmat, 2_pc, 4);
    circuit.addGate(dd::Zmat, 5_pc, 0);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Xmat, 3_pc, 5);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Xmat, 10_pc, 8);
    circuit.addGate(dd::Xmat, 4_pc, 2);
    circuit.addGate(dd::Zmat, 6_pc, 7);
    circuit.addGate(dd::Zmat, 7_pc, 9);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Zmat, 8_pc, 3);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 12 qubis, containing 36 Clifford gates.
TEST(LimTest, generatedCircuit_3) {
    dd::QuantumCircuit circuit(12);

    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Ymat, 9_pc, 4);
    circuit.addGate(dd::Xmat, 6_pc, 11);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Xmat, 10_pc, 6);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Ymat, 4_pc, 11);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Ymat, 4_pc, 7);
    circuit.addGate(dd::Xmat, 0_pc, 7);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Ymat, 7);
    circuit.addGate(dd::Ymat, 7_pc, 4);
    circuit.addGate(dd::Zmat, 2_pc, 3);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Xmat, 8_pc, 9);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Zmat, 1_pc, 0);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Zmat, 2_pc, 1);
    circuit.addGate(dd::Xmat, 8_pc, 7);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Zmat, 4_pc, 0);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Ymat, 11_pc, 7);
    circuit.addGate(dd::Zmat, 0_pc, 6);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 13 qubis, containing 39 Clifford gates.
TEST(LimTest, generatedCircuit_4) {
    dd::QuantumCircuit circuit(13);

    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Xmat, 4_pc, 7);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Zmat, 8_pc, 3);
    circuit.addGate(dd::Ymat, 4_pc, 1);
    circuit.addGate(dd::Zmat, 9_pc, 4);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Xmat, 4_pc, 9);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Xmat, 10_pc, 9);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Ymat, 10_pc, 12);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Ymat, 3_pc, 6);
    circuit.addGate(dd::Ymat, 5_pc, 11);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Xmat, 8_pc, 6);
    circuit.addGate(dd::Zmat, 9_pc, 1);
    circuit.addGate(dd::Zmat, 11_pc, 5);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Xmat, 3_pc, 7);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Ymat, 10_pc, 4);
    circuit.addGate(dd::Xmat, 4_pc, 12);
    circuit.addGate(dd::Ymat, 10_pc, 3);
    circuit.addGate(dd::Zmat, 1);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 14 qubis, containing 42 Clifford gates.
TEST(LimTest, generatedCircuit_5) {
    dd::QuantumCircuit circuit(14);

    circuit.addGate(dd::Xmat, 7_pc, 6);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Zmat, 9_pc, 3);
    circuit.addGate(dd::Xmat, 10_pc, 1);
    circuit.addGate(dd::Xmat, 3_pc, 1);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Smat, 13);
    circuit.addGate(dd::Xmat, 3_pc, 2);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Ymat, 4_pc, 10);
    circuit.addGate(dd::Ymat, 4_pc, 2);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Ymat, 0_pc, 5);
    circuit.addGate(dd::Ymat, 4_pc, 8);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Zmat, 11_pc, 10);
    circuit.addGate(dd::Xmat, 4_pc, 7);
    circuit.addGate(dd::Ymat, 9);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Xmat, 8_pc, 2);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Xmat, 2_pc, 5);
    circuit.addGate(dd::Ymat, 6_pc, 1);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Ymat, 2_pc, 13);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Ymat, 0_pc, 12);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Zmat, 1_pc, 11);
    circuit.addGate(dd::Zmat, 6_pc, 3);
    circuit.addGate(dd::Ymat, 10);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 15 qubis, containing 45 Clifford gates.
TEST(LimTest, generatedCircuit_6) {
    dd::QuantumCircuit circuit(15);

    circuit.addGate(dd::Zmat, 9_pc, 10);
    circuit.addGate(dd::Ymat, 11);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Zmat, 13);
    circuit.addGate(dd::Zmat, 11_pc, 10);
    circuit.addGate(dd::Zmat, 4_pc, 3);
    circuit.addGate(dd::Ymat, 4_pc, 13);
    circuit.addGate(dd::Ymat, 3_pc, 2);
    circuit.addGate(dd::Xmat, 1_pc, 4);
    circuit.addGate(dd::Xmat, 9_pc, 2);
    circuit.addGate(dd::Ymat, 8_pc, 0);
    circuit.addGate(dd::Xmat, 5_pc, 7);
    circuit.addGate(dd::Zmat, 3_pc, 5);
    circuit.addGate(dd::Zmat, 1_pc, 5);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Zmat, 13_pc, 14);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Ymat, 10);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Ymat, 9_pc, 14);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Ymat, 2_pc, 8);
    circuit.addGate(dd::Zmat, 9_pc, 3);
    circuit.addGate(dd::Xmat, 7_pc, 6);
    circuit.addGate(dd::Xmat, 11_pc, 5);
    circuit.addGate(dd::Ymat, 1_pc, 0);
    circuit.addGate(dd::Ymat, 10);
    circuit.addGate(dd::Zmat, 11_pc, 1);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Zmat, 12);
    circuit.addGate(dd::Ymat, 11);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Xmat, 7_pc, 4);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Ymat, 5_pc, 3);
    circuit.addGate(dd::Xmat, 12_pc, 9);
    circuit.addGate(dd::Xmat, 12_pc, 7);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Zmat, 4_pc, 3);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 16 qubis, containing 48 Clifford gates.
TEST(LimTest, generatedCircuit_7) {
    dd::QuantumCircuit circuit(16);

    circuit.addGate(dd::Zmat, 12_pc, 1);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Zmat, 4_pc, 3);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Ymat, 6_pc, 8);
    circuit.addGate(dd::Xmat, 3_pc, 6);
    circuit.addGate(dd::Ymat, 9);
    circuit.addGate(dd::Xmat, 15_pc, 10);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Xmat, 6_pc, 10);
    circuit.addGate(dd::Ymat, 11_pc, 8);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Zmat, 4_pc, 15);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Zmat, 2_pc, 0);
    circuit.addGate(dd::Zmat, 2_pc, 14);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Xmat, 7_pc, 6);
    circuit.addGate(dd::Zmat, 15_pc, 6);
    circuit.addGate(dd::Zmat, 14);
    circuit.addGate(dd::Xmat, 15);
    circuit.addGate(dd::Ymat, 1_pc, 4);
    circuit.addGate(dd::Ymat, 6_pc, 9);
    circuit.addGate(dd::Zmat, 1_pc, 7);
    circuit.addGate(dd::Xmat, 8_pc, 1);
    circuit.addGate(dd::Smat, 15);
    circuit.addGate(dd::Xmat, 12_pc, 13);
    circuit.addGate(dd::Ymat, 13);
    circuit.addGate(dd::Zmat, 12_pc, 7);
    circuit.addGate(dd::Xmat, 11_pc, 0);
    circuit.addGate(dd::Xmat, 11_pc, 10);
    circuit.addGate(dd::Xmat, 9_pc, 0);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Smat, 15);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Ymat, 14_pc, 2);
    circuit.addGate(dd::Zmat, 9_pc, 5);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Zmat, 5_pc, 11);
    circuit.addGate(dd::Ymat, 5_pc, 0);
    circuit.addGate(dd::Zmat, 1_pc, 14);
    circuit.addGate(dd::Ymat, 8_pc, 14);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 17 qubis, containing 51 Clifford gates.
TEST(LimTest, generatedCircuit_8) {
    dd::QuantumCircuit circuit(17);

    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Xmat, 1_pc, 15);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Zmat, 1_pc, 7);
    circuit.addGate(dd::Xmat, 8_pc, 6);
    circuit.addGate(dd::Ymat, 15);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Zmat, 0_pc, 1);
    circuit.addGate(dd::Zmat, 2_pc, 8);
    circuit.addGate(dd::Ymat, 0_pc, 5);
    circuit.addGate(dd::Hmat, 9);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Ymat, 6_pc, 13);
    circuit.addGate(dd::Xmat, 10_pc, 2);
    circuit.addGate(dd::Zmat, 1_pc, 7);
    circuit.addGate(dd::Xmat, 1_pc, 4);
    circuit.addGate(dd::Xmat, 15);
    circuit.addGate(dd::Xmat, 8_pc, 16);
    circuit.addGate(dd::Ymat, 11_pc, 10);
    circuit.addGate(dd::Xmat, 16);
    circuit.addGate(dd::Zmat, 13_pc, 2);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Zmat, 9_pc, 2);
    circuit.addGate(dd::Xmat, 6_pc, 0);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Xmat, 1_pc, 5);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Zmat, 14);
    circuit.addGate(dd::Zmat, 10_pc, 15);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Xmat, 6_pc, 12);
    circuit.addGate(dd::Zmat, 4_pc, 12);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Smat, 13);
    circuit.addGate(dd::Zmat, 3_pc, 14);
    circuit.addGate(dd::Zmat, 11_pc, 7);
    circuit.addGate(dd::Ymat, 0_pc, 2);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Ymat, 12_pc, 2);
    circuit.addGate(dd::Zmat, 7_pc, 2);
    circuit.addGate(dd::Ymat, 3_pc, 1);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Ymat, 9);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Ymat, 8_pc, 2);
    circuit.addGate(dd::Ymat, 15_pc, 10);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 18 qubis, containing 54 Clifford gates.
TEST(LimTest, generatedCircuit_9) {
    dd::QuantumCircuit circuit(18);

    circuit.addGate(dd::Xmat, 11_pc, 2);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Ymat, 6_pc, 11);
    circuit.addGate(dd::Xmat, 16_pc, 6);
    circuit.addGate(dd::Ymat, 11_pc, 15);
    circuit.addGate(dd::Xmat, 4_pc, 8);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Ymat, 1_pc, 15);
    circuit.addGate(dd::Zmat, 6_pc, 4);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Zmat, 0_pc, 10);
    circuit.addGate(dd::Xmat, 7_pc, 10);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Ymat, 2_pc, 10);
    circuit.addGate(dd::Hmat, 17);
    circuit.addGate(dd::Smat, 15);
    circuit.addGate(dd::Ymat, 11_pc, 8);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Ymat, 5_pc, 11);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Xmat, 12);
    circuit.addGate(dd::Zmat, 13_pc, 6);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Xmat, 9_pc, 7);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Zmat, 14);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Zmat, 15_pc, 0);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Zmat, 2_pc, 1);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Zmat, 13_pc, 0);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Zmat, 9_pc, 13);
    circuit.addGate(dd::Zmat, 17_pc, 7);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Ymat, 15);
    circuit.addGate(dd::Xmat, 3_pc, 8);
    circuit.addGate(dd::Xmat, 9_pc, 0);
    circuit.addGate(dd::Xmat, 17_pc, 14);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 19 qubis, containing 57 Clifford gates.
TEST(LimTest, generatedCircuit_10) {
    dd::QuantumCircuit circuit(19);

    circuit.addGate(dd::Zmat, 18_pc, 0);
    circuit.addGate(dd::Ymat, 16);
    circuit.addGate(dd::Xmat, 3_pc, 1);
    circuit.addGate(dd::Zmat, 8_pc, 7);
    circuit.addGate(dd::Ymat, 11_pc, 12);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Xmat, 12);
    circuit.addGate(dd::Zmat, 2_pc, 16);
    circuit.addGate(dd::Zmat, 18);
    circuit.addGate(dd::Zmat, 15);
    circuit.addGate(dd::Ymat, 10_pc, 11);
    circuit.addGate(dd::Zmat, 12);
    circuit.addGate(dd::Zmat, 1_pc, 9);
    circuit.addGate(dd::Smat, 17);
    circuit.addGate(dd::Ymat, 13);
    circuit.addGate(dd::Xmat, 5_pc, 10);
    circuit.addGate(dd::Xmat, 12);
    circuit.addGate(dd::Ymat, 16_pc, 2);
    circuit.addGate(dd::Zmat, 18);
    circuit.addGate(dd::Xmat, 6_pc, 17);
    circuit.addGate(dd::Ymat, 7_pc, 0);
    circuit.addGate(dd::Zmat, 6_pc, 8);
    circuit.addGate(dd::Zmat, 1_pc, 15);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Zmat, 13_pc, 17);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Ymat, 13_pc, 12);
    circuit.addGate(dd::Xmat, 0_pc, 2);
    circuit.addGate(dd::Hmat, 18);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Ymat, 14_pc, 3);
    circuit.addGate(dd::Ymat, 18);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Ymat, 11_pc, 2);
    circuit.addGate(dd::Xmat, 8_pc, 15);
    circuit.addGate(dd::Xmat, 9_pc, 2);
    circuit.addGate(dd::Xmat, 1_pc, 16);
    circuit.addGate(dd::Xmat, 17_pc, 3);
    circuit.addGate(dd::Ymat, 6_pc, 15);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Xmat, 1_pc, 17);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Ymat, 16);
    circuit.addGate(dd::Zmat, 3_pc, 13);
    circuit.addGate(dd::Zmat, 14_pc, 3);
    circuit.addGate(dd::Zmat, 0_pc, 3);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Xmat, 6_pc, 0);
    circuit.addGate(dd::Xmat, 0_pc, 6);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Xmat, 6_pc, 3);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Zmat, 8_pc, 3);
    circuit.addGate(dd::Ymat, 3_pc, 17);
    circuit.addGate(dd::Xmat, 4_pc, 9);
    circuit.addGate(dd::Hmat, 12);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 20 qubis, containing 60 Clifford gates.
TEST(LimTest, generatedCircuit_11) {
    dd::QuantumCircuit circuit(20);

    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Zmat, 10_pc, 2);
    circuit.addGate(dd::Ymat, 9);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Xmat, 11_pc, 5);
    circuit.addGate(dd::Ymat, 1_pc, 12);
    circuit.addGate(dd::Smat, 14);
    circuit.addGate(dd::Xmat, 6_pc, 2);
    circuit.addGate(dd::Ymat, 2);
    circuit.addGate(dd::Hmat, 16);
    circuit.addGate(dd::Xmat, 19_pc, 5);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Xmat, 14_pc, 13);
    circuit.addGate(dd::Smat, 14);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Ymat, 16);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Xmat, 8_pc, 10);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Ymat, 7_pc, 5);
    circuit.addGate(dd::Ymat, 9_pc, 8);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Xmat, 13_pc, 7);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Zmat, 19_pc, 8);
    circuit.addGate(dd::Smat, 17);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Xmat, 3_pc, 10);
    circuit.addGate(dd::Xmat, 16);
    circuit.addGate(dd::Zmat, 9_pc, 2);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Smat, 19);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Xmat, 6_pc, 12);
    circuit.addGate(dd::Smat, 17);
    circuit.addGate(dd::Zmat, 1_pc, 17);
    circuit.addGate(dd::Zmat, 13);
    circuit.addGate(dd::Smat, 18);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Xmat, 19_pc, 6);
    circuit.addGate(dd::Xmat, 6_pc, 17);
    circuit.addGate(dd::Ymat, 2);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Zmat, 4_pc, 14);
    circuit.addGate(dd::Zmat, 12);
    circuit.addGate(dd::Ymat, 17);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Smat, 12);
    circuit.addGate(dd::Zmat, 11_pc, 4);
    circuit.addGate(dd::Ymat, 19_pc, 13);
    circuit.addGate(dd::Smat, 19);
    circuit.addGate(dd::Smat, 4);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 21 qubis, containing 63 Clifford gates.
TEST(LimTest, generatedCircuit_12) {
    dd::QuantumCircuit circuit(21);

    circuit.addGate(dd::Zmat, 18);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Zmat, 20_pc, 17);
    circuit.addGate(dd::Ymat, 7);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Zmat, 14_pc, 13);
    circuit.addGate(dd::Zmat, 6);
    circuit.addGate(dd::Zmat, 6_pc, 8);
    circuit.addGate(dd::Xmat, 18_pc, 4);
    circuit.addGate(dd::Xmat, 5_pc, 3);
    circuit.addGate(dd::Zmat, 20_pc, 16);
    circuit.addGate(dd::Ymat, 0_pc, 15);
    circuit.addGate(dd::Zmat, 5_pc, 19);
    circuit.addGate(dd::Xmat, 12);
    circuit.addGate(dd::Xmat, 17);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Ymat, 2_pc, 1);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Ymat, 7_pc, 6);
    circuit.addGate(dd::Xmat, 20_pc, 16);
    circuit.addGate(dd::Zmat, 10_pc, 0);
    circuit.addGate(dd::Hmat, 19);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Ymat, 4_pc, 8);
    circuit.addGate(dd::Smat, 16);
    circuit.addGate(dd::Ymat, 15);
    circuit.addGate(dd::Ymat, 20);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Zmat, 20);
    circuit.addGate(dd::Zmat, 18);
    circuit.addGate(dd::Ymat, 16);
    circuit.addGate(dd::Zmat, 1_pc, 15);
    circuit.addGate(dd::Ymat, 2);
    circuit.addGate(dd::Xmat, 16_pc, 6);
    circuit.addGate(dd::Ymat, 0_pc, 8);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Ymat, 18);
    circuit.addGate(dd::Xmat, 15_pc, 3);
    circuit.addGate(dd::Xmat, 15);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Xmat, 10_pc, 6);
    circuit.addGate(dd::Smat, 10);
    circuit.addGate(dd::Zmat, 10_pc, 8);
    circuit.addGate(dd::Hmat, 20);
    circuit.addGate(dd::Hmat, 13);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Zmat, 17_pc, 19);
    circuit.addGate(dd::Zmat, 6_pc, 0);
    circuit.addGate(dd::Ymat, 10);
    circuit.addGate(dd::Zmat, 18_pc, 15);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Hmat, 15);
    circuit.addGate(dd::Hmat, 16);
    circuit.addGate(dd::Zmat, 1_pc, 17);
    circuit.addGate(dd::Xmat, 19);
    circuit.addGate(dd::Zmat, 13_pc, 17);
    circuit.addGate(dd::Xmat, 15_pc, 11);
    circuit.addGate(dd::Ymat, 0_pc, 15);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Xmat, 8_pc, 12);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 22 qubis, containing 66 Clifford gates.
TEST(LimTest, generatedCircuit_13) {
    dd::QuantumCircuit circuit(22);

    circuit.addGate(dd::Ymat, 10_pc, 16);
    circuit.addGate(dd::Xmat, 4_pc, 13);
    circuit.addGate(dd::Ymat, 14);
    circuit.addGate(dd::Ymat, 13_pc, 11);
    circuit.addGate(dd::Xmat, 18);
    circuit.addGate(dd::Zmat, 2_pc, 19);
    circuit.addGate(dd::Ymat, 9_pc, 4);
    circuit.addGate(dd::Ymat, 0_pc, 4);
    circuit.addGate(dd::Ymat, 10);
    circuit.addGate(dd::Ymat, 16);
    circuit.addGate(dd::Ymat, 7_pc, 15);
    circuit.addGate(dd::Ymat, 9_pc, 8);
    circuit.addGate(dd::Ymat, 11_pc, 5);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Xmat, 7_pc, 21);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Ymat, 9_pc, 15);
    circuit.addGate(dd::Ymat, 0_pc, 20);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Smat, 11);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Ymat, 20_pc, 12);
    circuit.addGate(dd::Ymat, 18_pc, 5);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Ymat, 13_pc, 2);
    circuit.addGate(dd::Xmat, 15);
    circuit.addGate(dd::Hmat, 13);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Zmat, 13_pc, 8);
    circuit.addGate(dd::Ymat, 20);
    circuit.addGate(dd::Ymat, 18_pc, 20);
    circuit.addGate(dd::Xmat, 16_pc, 10);
    circuit.addGate(dd::Xmat, 21_pc, 0);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Xmat, 18_pc, 9);
    circuit.addGate(dd::Xmat, 21);
    circuit.addGate(dd::Zmat, 18_pc, 7);
    circuit.addGate(dd::Xmat, 10_pc, 18);
    circuit.addGate(dd::Hmat, 20);
    circuit.addGate(dd::Zmat, 5_pc, 4);
    circuit.addGate(dd::Ymat, 1_pc, 2);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Ymat, 21);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Zmat, 5_pc, 4);
    circuit.addGate(dd::Xmat, 11_pc, 6);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Zmat, 3_pc, 5);
    circuit.addGate(dd::Zmat, 5);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Smat, 10);
    circuit.addGate(dd::Ymat, 16_pc, 17);
    circuit.addGate(dd::Zmat, 0_pc, 6);
    circuit.addGate(dd::Ymat, 14_pc, 18);
    circuit.addGate(dd::Zmat, 11_pc, 12);
    circuit.addGate(dd::Ymat, 19);
    circuit.addGate(dd::Ymat, 5_pc, 7);
    circuit.addGate(dd::Xmat, 15_pc, 7);
    circuit.addGate(dd::Ymat, 11_pc, 7);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 23 qubis, containing 69 Clifford gates.
TEST(LimTest, generatedCircuit_14) {
    dd::QuantumCircuit circuit(23);

    circuit.addGate(dd::Smat, 12);
    circuit.addGate(dd::Ymat, 17);
    circuit.addGate(dd::Xmat, 9_pc, 6);
    circuit.addGate(dd::Ymat, 12_pc, 11);
    circuit.addGate(dd::Zmat, 10_pc, 16);
    circuit.addGate(dd::Xmat, 20_pc, 11);
    circuit.addGate(dd::Zmat, 17);
    circuit.addGate(dd::Xmat, 9_pc, 4);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Smat, 11);
    circuit.addGate(dd::Hmat, 17);
    circuit.addGate(dd::Ymat, 0_pc, 7);
    circuit.addGate(dd::Ymat, 11);
    circuit.addGate(dd::Xmat, 9_pc, 16);
    circuit.addGate(dd::Smat, 16);
    circuit.addGate(dd::Smat, 14);
    circuit.addGate(dd::Zmat, 6_pc, 18);
    circuit.addGate(dd::Xmat, 13);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Ymat, 20_pc, 2);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Xmat, 7_pc, 21);
    circuit.addGate(dd::Xmat, 1_pc, 11);
    circuit.addGate(dd::Zmat, 21);
    circuit.addGate(dd::Zmat, 6);
    circuit.addGate(dd::Ymat, 12_pc, 20);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Zmat, 5_pc, 9);
    circuit.addGate(dd::Zmat, 6);
    circuit.addGate(dd::Ymat, 13);
    circuit.addGate(dd::Ymat, 17);
    circuit.addGate(dd::Zmat, 17_pc, 22);
    circuit.addGate(dd::Smat, 12);
    circuit.addGate(dd::Xmat, 4_pc, 18);
    circuit.addGate(dd::Zmat, 0_pc, 18);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Zmat, 10_pc, 5);
    circuit.addGate(dd::Xmat, 12_pc, 9);
    circuit.addGate(dd::Xmat, 20_pc, 18);
    circuit.addGate(dd::Zmat, 11_pc, 14);
    circuit.addGate(dd::Ymat, 7_pc, 1);
    circuit.addGate(dd::Smat, 19);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Smat, 15);
    circuit.addGate(dd::Xmat, 8_pc, 22);
    circuit.addGate(dd::Hmat, 15);
    circuit.addGate(dd::Zmat, 1_pc, 4);
    circuit.addGate(dd::Zmat, 22_pc, 15);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Zmat, 7_pc, 10);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Xmat, 20);
    circuit.addGate(dd::Zmat, 12_pc, 3);
    circuit.addGate(dd::Ymat, 2);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Ymat, 21_pc, 6);
    circuit.addGate(dd::Xmat, 10_pc, 17);
    circuit.addGate(dd::Smat, 18);
    circuit.addGate(dd::Ymat, 17);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Xmat, 3_pc, 22);
    circuit.addGate(dd::Zmat, 13_pc, 8);
    circuit.addGate(dd::Ymat, 17_pc, 16);
    circuit.addGate(dd::Xmat, 11_pc, 5);
    circuit.addGate(dd::Smat, 10);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 24 qubis, containing 72 Clifford gates.
TEST(LimTest, generatedCircuit_15) {
    dd::QuantumCircuit circuit(24);

    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Xmat, 10_pc, 17);
    circuit.addGate(dd::Zmat, 2_pc, 23);
    circuit.addGate(dd::Xmat, 21);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Xmat, 3);
    circuit.addGate(dd::Ymat, 9_pc, 15);
    circuit.addGate(dd::Zmat, 7_pc, 20);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Ymat, 14);
    circuit.addGate(dd::Zmat, 17_pc, 6);
    circuit.addGate(dd::Ymat, 0_pc, 20);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Ymat, 9);
    circuit.addGate(dd::Smat, 12);
    circuit.addGate(dd::Zmat, 13_pc, 6);
    circuit.addGate(dd::Xmat, 5_pc, 9);
    circuit.addGate(dd::Xmat, 14_pc, 7);
    circuit.addGate(dd::Hmat, 21);
    circuit.addGate(dd::Zmat, 19);
    circuit.addGate(dd::Ymat, 12_pc, 9);
    circuit.addGate(dd::Xmat, 18_pc, 9);
    circuit.addGate(dd::Xmat, 5_pc, 20);
    circuit.addGate(dd::Xmat, 10_pc, 20);
    circuit.addGate(dd::Xmat, 3_pc, 1);
    circuit.addGate(dd::Ymat, 10_pc, 15);
    circuit.addGate(dd::Ymat, 4_pc, 14);
    circuit.addGate(dd::Ymat, 19_pc, 10);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Hmat, 20);
    circuit.addGate(dd::Xmat, 18_pc, 23);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Hmat, 17);
    circuit.addGate(dd::Xmat, 19_pc, 15);
    circuit.addGate(dd::Ymat, 6_pc, 3);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Smat, 15);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Zmat, 11_pc, 22);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Ymat, 23_pc, 15);
    circuit.addGate(dd::Zmat, 22);
    circuit.addGate(dd::Xmat, 14_pc, 6);
    circuit.addGate(dd::Smat, 21);
    circuit.addGate(dd::Xmat, 18_pc, 15);
    circuit.addGate(dd::Ymat, 7_pc, 13);
    circuit.addGate(dd::Xmat, 1_pc, 17);
    circuit.addGate(dd::Ymat, 11);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Hmat, 16);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Ymat, 20_pc, 7);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Xmat, 14_pc, 23);
    circuit.addGate(dd::Ymat, 22);
    circuit.addGate(dd::Ymat, 4_pc, 2);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Smat, 10);
    circuit.addGate(dd::Ymat, 17);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Ymat, 7_pc, 16);
    circuit.addGate(dd::Ymat, 12_pc, 9);
    circuit.addGate(dd::Smat, 10);
    circuit.addGate(dd::Ymat, 20_pc, 15);
    circuit.addGate(dd::Xmat, 18_pc, 19);
    circuit.addGate(dd::Ymat, 5_pc, 23);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 25 qubis, containing 75 Clifford gates.
TEST(LimTest, generatedCircuit_16) {
    dd::QuantumCircuit circuit(25);

    circuit.addGate(dd::Zmat, 18);
    circuit.addGate(dd::Xmat, 18_pc, 19);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Ymat, 0_pc, 24);
    circuit.addGate(dd::Zmat, 20_pc, 11);
    circuit.addGate(dd::Ymat, 22_pc, 6);
    circuit.addGate(dd::Xmat, 5_pc, 18);
    circuit.addGate(dd::Ymat, 22_pc, 19);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Xmat, 0_pc, 8);
    circuit.addGate(dd::Ymat, 22_pc, 1);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Ymat, 20_pc, 22);
    circuit.addGate(dd::Ymat, 21_pc, 18);
    circuit.addGate(dd::Hmat, 23);
    circuit.addGate(dd::Ymat, 24_pc, 5);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Ymat, 14_pc, 23);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Ymat, 1);
    circuit.addGate(dd::Zmat, 23);
    circuit.addGate(dd::Xmat, 5_pc, 4);
    circuit.addGate(dd::Xmat, 0_pc, 21);
    circuit.addGate(dd::Ymat, 20);
    circuit.addGate(dd::Xmat, 13);
    circuit.addGate(dd::Xmat, 20_pc, 9);
    circuit.addGate(dd::Xmat, 1_pc, 24);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Zmat, 3);
    circuit.addGate(dd::Xmat, 17);
    circuit.addGate(dd::Zmat, 12_pc, 9);
    circuit.addGate(dd::Zmat, 15_pc, 18);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Ymat, 13);
    circuit.addGate(dd::Smat, 1);
    circuit.addGate(dd::Xmat, 23_pc, 7);
    circuit.addGate(dd::Zmat, 22_pc, 13);
    circuit.addGate(dd::Hmat, 19);
    circuit.addGate(dd::Xmat, 13);
    circuit.addGate(dd::Xmat, 2_pc, 19);
    circuit.addGate(dd::Xmat, 9_pc, 18);
    circuit.addGate(dd::Xmat, 18_pc, 6);
    circuit.addGate(dd::Ymat, 3_pc, 14);
    circuit.addGate(dd::Ymat, 11_pc, 9);
    circuit.addGate(dd::Xmat, 15_pc, 5);
    circuit.addGate(dd::Smat, 17);
    circuit.addGate(dd::Xmat, 12_pc, 13);
    circuit.addGate(dd::Ymat, 16_pc, 20);
    circuit.addGate(dd::Xmat, 5_pc, 9);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Zmat, 12_pc, 0);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Xmat, 12);
    circuit.addGate(dd::Zmat, 17_pc, 6);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Smat, 20);
    circuit.addGate(dd::Ymat, 11_pc, 21);
    circuit.addGate(dd::Hmat, 3);
    circuit.addGate(dd::Smat, 13);
    circuit.addGate(dd::Xmat, 19);
    circuit.addGate(dd::Ymat, 15_pc, 9);
    circuit.addGate(dd::Zmat, 21);
    circuit.addGate(dd::Zmat, 24);
    circuit.addGate(dd::Zmat, 11_pc, 7);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Ymat, 22);
    circuit.addGate(dd::Zmat, 4_pc, 19);
    circuit.addGate(dd::Zmat, 9_pc, 8);
    circuit.addGate(dd::Xmat, 3_pc, 2);
    circuit.addGate(dd::Xmat, 13_pc, 2);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 26 qubis, containing 78 Clifford gates.
TEST(LimTest, generatedCircuit_17) {
    dd::QuantumCircuit circuit(26);

    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Ymat, 20);
    circuit.addGate(dd::Ymat, 25_pc, 15);
    circuit.addGate(dd::Zmat, 21_pc, 24);
    circuit.addGate(dd::Xmat, 25_pc, 3);
    circuit.addGate(dd::Zmat, 24_pc, 18);
    circuit.addGate(dd::Smat, 11);
    circuit.addGate(dd::Hmat, 25);
    circuit.addGate(dd::Ymat, 19_pc, 16);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Xmat, 21_pc, 18);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Ymat, 6_pc, 16);
    circuit.addGate(dd::Xmat, 21_pc, 22);
    circuit.addGate(dd::Xmat, 17_pc, 22);
    circuit.addGate(dd::Ymat, 14_pc, 25);
    circuit.addGate(dd::Ymat, 16);
    circuit.addGate(dd::Zmat, 3_pc, 15);
    circuit.addGate(dd::Smat, 10);
    circuit.addGate(dd::Ymat, 22_pc, 0);
    circuit.addGate(dd::Ymat, 6_pc, 13);
    circuit.addGate(dd::Xmat, 9_pc, 16);
    circuit.addGate(dd::Xmat, 7_pc, 3);
    circuit.addGate(dd::Hmat, 19);
    circuit.addGate(dd::Ymat, 6_pc, 22);
    circuit.addGate(dd::Zmat, 25_pc, 20);
    circuit.addGate(dd::Xmat, 24_pc, 16);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Xmat, 18_pc, 3);
    circuit.addGate(dd::Zmat, 17_pc, 0);
    circuit.addGate(dd::Smat, 7);
    circuit.addGate(dd::Ymat, 11_pc, 24);
    circuit.addGate(dd::Ymat, 16);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Ymat, 2);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Xmat, 3_pc, 9);
    circuit.addGate(dd::Zmat, 11_pc, 25);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Ymat, 0_pc, 16);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Ymat, 19_pc, 25);
    circuit.addGate(dd::Xmat, 3_pc, 13);
    circuit.addGate(dd::Ymat, 16_pc, 0);
    circuit.addGate(dd::Ymat, 10_pc, 2);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Zmat, 21_pc, 7);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Ymat, 20);
    circuit.addGate(dd::Ymat, 19_pc, 25);
    circuit.addGate(dd::Smat, 24);
    circuit.addGate(dd::Xmat, 12_pc, 16);
    circuit.addGate(dd::Zmat, 18_pc, 12);
    circuit.addGate(dd::Xmat, 17_pc, 11);
    circuit.addGate(dd::Xmat, 20_pc, 8);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Xmat, 23_pc, 2);
    circuit.addGate(dd::Zmat, 21);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Hmat, 24);
    circuit.addGate(dd::Zmat, 18_pc, 15);
    circuit.addGate(dd::Zmat, 8_pc, 12);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Zmat, 9_pc, 3);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Zmat, 25);
    circuit.addGate(dd::Xmat, 24);
    circuit.addGate(dd::Smat, 20);
    circuit.addGate(dd::Xmat, 2_pc, 7);
    circuit.addGate(dd::Ymat, 0_pc, 23);
    circuit.addGate(dd::Zmat, 7_pc, 3);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Xmat, 20_pc, 24);
    circuit.addGate(dd::Ymat, 1_pc, 14);
    circuit.addGate(dd::Zmat, 8);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 27 qubis, containing 81 Clifford gates.
TEST(LimTest, generatedCircuit_18) {
    dd::QuantumCircuit circuit(27);

    circuit.addGate(dd::Xmat, 20);
    circuit.addGate(dd::Zmat, 5_pc, 22);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Xmat, 0_pc, 23);
    circuit.addGate(dd::Ymat, 23_pc, 14);
    circuit.addGate(dd::Hmat, 2);
    circuit.addGate(dd::Ymat, 13);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Ymat, 26_pc, 10);
    circuit.addGate(dd::Zmat, 8_pc, 26);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Zmat, 24_pc, 7);
    circuit.addGate(dd::Xmat, 18_pc, 17);
    circuit.addGate(dd::Xmat, 20_pc, 0);
    circuit.addGate(dd::Hmat, 24);
    circuit.addGate(dd::Ymat, 2_pc, 1);
    circuit.addGate(dd::Zmat, 24);
    circuit.addGate(dd::Hmat, 17);
    circuit.addGate(dd::Xmat, 5);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Ymat, 22);
    circuit.addGate(dd::Xmat, 4_pc, 22);
    circuit.addGate(dd::Xmat, 25_pc, 15);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Zmat, 15_pc, 26);
    circuit.addGate(dd::Ymat, 23);
    circuit.addGate(dd::Zmat, 2);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Ymat, 5_pc, 6);
    circuit.addGate(dd::Smat, 21);
    circuit.addGate(dd::Zmat, 6_pc, 19);
    circuit.addGate(dd::Ymat, 7_pc, 24);
    circuit.addGate(dd::Smat, 25);
    circuit.addGate(dd::Zmat, 13);
    circuit.addGate(dd::Ymat, 18_pc, 9);
    circuit.addGate(dd::Xmat, 11_pc, 13);
    circuit.addGate(dd::Zmat, 0_pc, 10);
    circuit.addGate(dd::Smat, 20);
    circuit.addGate(dd::Xmat, 18_pc, 22);
    circuit.addGate(dd::Zmat, 4_pc, 5);
    circuit.addGate(dd::Zmat, 4_pc, 12);
    circuit.addGate(dd::Ymat, 26_pc, 18);
    circuit.addGate(dd::Ymat, 9_pc, 22);
    circuit.addGate(dd::Ymat, 23_pc, 20);
    circuit.addGate(dd::Zmat, 20_pc, 23);
    circuit.addGate(dd::Xmat, 16);
    circuit.addGate(dd::Zmat, 23_pc, 3);
    circuit.addGate(dd::Smat, 23);
    circuit.addGate(dd::Xmat, 13_pc, 10);
    circuit.addGate(dd::Xmat, 0_pc, 3);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Smat, 5);
    circuit.addGate(dd::Smat, 25);
    circuit.addGate(dd::Xmat, 7);
    circuit.addGate(dd::Xmat, 12);
    circuit.addGate(dd::Ymat, 12_pc, 10);
    circuit.addGate(dd::Ymat, 21_pc, 11);
    circuit.addGate(dd::Xmat, 25_pc, 3);
    circuit.addGate(dd::Xmat, 20);
    circuit.addGate(dd::Zmat, 23_pc, 22);
    circuit.addGate(dd::Ymat, 16_pc, 10);
    circuit.addGate(dd::Smat, 23);
    circuit.addGate(dd::Smat, 16);
    circuit.addGate(dd::Xmat, 3_pc, 23);
    circuit.addGate(dd::Zmat, 11_pc, 0);
    circuit.addGate(dd::Smat, 20);
    circuit.addGate(dd::Hmat, 13);
    circuit.addGate(dd::Hmat, 22);
    circuit.addGate(dd::Xmat, 18_pc, 23);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Xmat, 16_pc, 24);
    circuit.addGate(dd::Ymat, 2_pc, 4);
    circuit.addGate(dd::Ymat, 0_pc, 15);
    circuit.addGate(dd::Ymat, 5_pc, 10);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Xmat, 12_pc, 0);
    circuit.addGate(dd::Ymat, 7);
    circuit.addGate(dd::Zmat, 24_pc, 20);
    circuit.addGate(dd::Ymat, 20_pc, 26);
    circuit.addGate(dd::Ymat, 15);
    circuit.addGate(dd::Xmat, 17_pc, 2);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 28 qubis, containing 84 Clifford gates.
TEST(LimTest, generatedCircuit_19) {
    dd::QuantumCircuit circuit(28);

    circuit.addGate(dd::Ymat, 20);
    circuit.addGate(dd::Smat, 20);
    circuit.addGate(dd::Xmat, 10);
    circuit.addGate(dd::Smat, 9);
    circuit.addGate(dd::Zmat, 26);
    circuit.addGate(dd::Zmat, 14_pc, 8);
    circuit.addGate(dd::Ymat, 14);
    circuit.addGate(dd::Ymat, 9_pc, 2);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Ymat, 10);
    circuit.addGate(dd::Smat, 27);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Ymat, 7_pc, 0);
    circuit.addGate(dd::Xmat, 7_pc, 11);
    circuit.addGate(dd::Zmat, 9_pc, 25);
    circuit.addGate(dd::Smat, 11);
    circuit.addGate(dd::Ymat, 21_pc, 25);
    circuit.addGate(dd::Ymat, 19_pc, 23);
    circuit.addGate(dd::Xmat, 15);
    circuit.addGate(dd::Ymat, 21_pc, 19);
    circuit.addGate(dd::Ymat, 23);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Xmat, 13_pc, 8);
    circuit.addGate(dd::Ymat, 4_pc, 6);
    circuit.addGate(dd::Zmat, 16_pc, 14);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Xmat, 9_pc, 26);
    circuit.addGate(dd::Zmat, 1);
    circuit.addGate(dd::Xmat, 24_pc, 19);
    circuit.addGate(dd::Zmat, 25);
    circuit.addGate(dd::Smat, 8);
    circuit.addGate(dd::Ymat, 16_pc, 10);
    circuit.addGate(dd::Ymat, 0_pc, 13);
    circuit.addGate(dd::Ymat, 27_pc, 22);
    circuit.addGate(dd::Hmat, 7);
    circuit.addGate(dd::Zmat, 5_pc, 24);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Hmat, 14);
    circuit.addGate(dd::Ymat, 23);
    circuit.addGate(dd::Xmat, 15_pc, 4);
    circuit.addGate(dd::Zmat, 14);
    circuit.addGate(dd::Xmat, 14_pc, 2);
    circuit.addGate(dd::Zmat, 14_pc, 27);
    circuit.addGate(dd::Zmat, 6_pc, 0);
    circuit.addGate(dd::Xmat, 8_pc, 21);
    circuit.addGate(dd::Xmat, 7_pc, 2);
    circuit.addGate(dd::Xmat, 7_pc, 24);
    circuit.addGate(dd::Zmat, 11_pc, 27);
    circuit.addGate(dd::Smat, 25);
    circuit.addGate(dd::Ymat, 11);
    circuit.addGate(dd::Ymat, 26);
    circuit.addGate(dd::Hmat, 21);
    circuit.addGate(dd::Ymat, 22_pc, 10);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Xmat, 11_pc, 24);
    circuit.addGate(dd::Xmat, 3_pc, 0);
    circuit.addGate(dd::Xmat, 23);
    circuit.addGate(dd::Xmat, 22_pc, 20);
    circuit.addGate(dd::Hmat, 16);
    circuit.addGate(dd::Ymat, 14);
    circuit.addGate(dd::Zmat, 8_pc, 6);
    circuit.addGate(dd::Hmat, 1);
    circuit.addGate(dd::Xmat, 5_pc, 0);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Zmat, 23);
    circuit.addGate(dd::Smat, 15);
    circuit.addGate(dd::Xmat, 3_pc, 24);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Zmat, 27);
    circuit.addGate(dd::Ymat, 13_pc, 9);
    circuit.addGate(dd::Ymat, 7_pc, 8);
    circuit.addGate(dd::Zmat, 25_pc, 1);
    circuit.addGate(dd::Ymat, 22);
    circuit.addGate(dd::Smat, 17);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Zmat, 19_pc, 3);
    circuit.addGate(dd::Hmat, 21);
    circuit.addGate(dd::Xmat, 20_pc, 26);
    circuit.addGate(dd::Ymat, 19);
    circuit.addGate(dd::Xmat, 26_pc, 11);
    circuit.addGate(dd::Zmat, 8_pc, 2);
    circuit.addGate(dd::Zmat, 24_pc, 27);
    circuit.addGate(dd::Zmat, 21_pc, 27);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 29 qubis, containing 87 Clifford gates.
TEST(LimTest, generatedCircuit_20) {
    dd::QuantumCircuit circuit(29);

    circuit.addGate(dd::Hmat, 8);
    circuit.addGate(dd::Ymat, 23);
    circuit.addGate(dd::Hmat, 13);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Hmat, 12);
    circuit.addGate(dd::Zmat, 27_pc, 9);
    circuit.addGate(dd::Xmat, 1_pc, 12);
    circuit.addGate(dd::Ymat, 9_pc, 18);
    circuit.addGate(dd::Ymat, 8_pc, 3);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Smat, 22);
    circuit.addGate(dd::Xmat, 22);
    circuit.addGate(dd::Hmat, 17);
    circuit.addGate(dd::Ymat, 22_pc, 2);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Ymat, 5_pc, 12);
    circuit.addGate(dd::Zmat, 14_pc, 8);
    circuit.addGate(dd::Ymat, 17);
    circuit.addGate(dd::Zmat, 26_pc, 3);
    circuit.addGate(dd::Xmat, 26_pc, 18);
    circuit.addGate(dd::Smat, 18);
    circuit.addGate(dd::Ymat, 4_pc, 14);
    circuit.addGate(dd::Xmat, 27);
    circuit.addGate(dd::Xmat, 20_pc, 1);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Ymat, 8_pc, 5);
    circuit.addGate(dd::Ymat, 12_pc, 14);
    circuit.addGate(dd::Ymat, 14);
    circuit.addGate(dd::Ymat, 14);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Xmat, 19_pc, 4);
    circuit.addGate(dd::Xmat, 1_pc, 18);
    circuit.addGate(dd::Hmat, 26);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Ymat, 5_pc, 2);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Smat, 18);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Xmat, 15_pc, 8);
    circuit.addGate(dd::Xmat, 19);
    circuit.addGate(dd::Ymat, 28);
    circuit.addGate(dd::Zmat, 21_pc, 20);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Ymat, 22_pc, 18);
    circuit.addGate(dd::Xmat, 26_pc, 7);
    circuit.addGate(dd::Zmat, 26_pc, 5);
    circuit.addGate(dd::Ymat, 8);
    circuit.addGate(dd::Ymat, 8_pc, 27);
    circuit.addGate(dd::Xmat, 14);
    circuit.addGate(dd::Hmat, 11);
    circuit.addGate(dd::Hmat, 23);
    circuit.addGate(dd::Xmat, 21);
    circuit.addGate(dd::Ymat, 7_pc, 23);
    circuit.addGate(dd::Xmat, 20);
    circuit.addGate(dd::Ymat, 24);
    circuit.addGate(dd::Xmat, 21);
    circuit.addGate(dd::Zmat, 20_pc, 16);
    circuit.addGate(dd::Xmat, 17_pc, 24);
    circuit.addGate(dd::Ymat, 6_pc, 25);
    circuit.addGate(dd::Xmat, 26);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Xmat, 26_pc, 14);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Smat, 20);
    circuit.addGate(dd::Ymat, 20_pc, 28);
    circuit.addGate(dd::Ymat, 4);
    circuit.addGate(dd::Ymat, 28_pc, 14);
    circuit.addGate(dd::Zmat, 21);
    circuit.addGate(dd::Ymat, 5);
    circuit.addGate(dd::Ymat, 3_pc, 9);
    circuit.addGate(dd::Smat, 6);
    circuit.addGate(dd::Smat, 15);
    circuit.addGate(dd::Ymat, 12);
    circuit.addGate(dd::Zmat, 22);
    circuit.addGate(dd::Ymat, 2);
    circuit.addGate(dd::Ymat, 21);
    circuit.addGate(dd::Xmat, 27);
    circuit.addGate(dd::Zmat, 11);
    circuit.addGate(dd::Ymat, 17_pc, 14);
    circuit.addGate(dd::Zmat, 15_pc, 9);
    circuit.addGate(dd::Ymat, 12_pc, 23);
    circuit.addGate(dd::Ymat, 26_pc, 4);
    circuit.addGate(dd::Ymat, 26_pc, 0);
    circuit.addGate(dd::Zmat, 19_pc, 23);
    circuit.addGate(dd::Zmat, 15_pc, 2);
    circuit.addGate(dd::Xmat, 14_pc, 16);
    circuit.addGate(dd::Ymat, 22_pc, 9);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 30 qubis, containing 90 Clifford gates.
TEST(LimTest, generatedCircuit_21) {
    dd::QuantumCircuit circuit(30);

    circuit.addGate(dd::Zmat, 25);
    circuit.addGate(dd::Zmat, 13_pc, 22);
    circuit.addGate(dd::Zmat, 10_pc, 11);
    circuit.addGate(dd::Zmat, 12_pc, 26);
    circuit.addGate(dd::Xmat, 21);
    circuit.addGate(dd::Zmat, 9);
    circuit.addGate(dd::Smat, 23);
    circuit.addGate(dd::Xmat, 4);
    circuit.addGate(dd::Xmat, 27_pc, 9);
    circuit.addGate(dd::Xmat, 22_pc, 17);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Hmat, 10);
    circuit.addGate(dd::Zmat, 22_pc, 1);
    circuit.addGate(dd::Hmat, 6);
    circuit.addGate(dd::Zmat, 1_pc, 20);
    circuit.addGate(dd::Xmat, 14_pc, 6);
    circuit.addGate(dd::Xmat, 23_pc, 13);
    circuit.addGate(dd::Xmat, 22_pc, 9);
    circuit.addGate(dd::Ymat, 15_pc, 1);
    circuit.addGate(dd::Zmat, 20);
    circuit.addGate(dd::Xmat, 21);
    circuit.addGate(dd::Ymat, 19);
    circuit.addGate(dd::Ymat, 20_pc, 11);
    circuit.addGate(dd::Ymat, 25_pc, 11);
    circuit.addGate(dd::Zmat, 26_pc, 20);
    circuit.addGate(dd::Xmat, 12_pc, 27);
    circuit.addGate(dd::Xmat, 10_pc, 7);
    circuit.addGate(dd::Xmat, 23_pc, 16);
    circuit.addGate(dd::Xmat, 18_pc, 6);
    circuit.addGate(dd::Zmat, 26_pc, 20);
    circuit.addGate(dd::Smat, 2);
    circuit.addGate(dd::Ymat, 19_pc, 2);
    circuit.addGate(dd::Xmat, 28);
    circuit.addGate(dd::Smat, 3);
    circuit.addGate(dd::Zmat, 24_pc, 28);
    circuit.addGate(dd::Smat, 19);
    circuit.addGate(dd::Zmat, 6_pc, 27);
    circuit.addGate(dd::Ymat, 3);
    circuit.addGate(dd::Smat, 21);
    circuit.addGate(dd::Xmat, 0);
    circuit.addGate(dd::Hmat, 4);
    circuit.addGate(dd::Zmat, 8);
    circuit.addGate(dd::Ymat, 11_pc, 19);
    circuit.addGate(dd::Xmat, 16_pc, 12);
    circuit.addGate(dd::Hmat, 5);
    circuit.addGate(dd::Smat, 22);
    circuit.addGate(dd::Xmat, 21);
    circuit.addGate(dd::Smat, 19);
    circuit.addGate(dd::Xmat, 29);
    circuit.addGate(dd::Zmat, 4);
    circuit.addGate(dd::Zmat, 28_pc, 11);
    circuit.addGate(dd::Xmat, 26_pc, 20);
    circuit.addGate(dd::Smat, 0);
    circuit.addGate(dd::Xmat, 8);
    circuit.addGate(dd::Ymat, 28_pc, 21);
    circuit.addGate(dd::Xmat, 8_pc, 28);
    circuit.addGate(dd::Ymat, 17_pc, 9);
    circuit.addGate(dd::Hmat, 27);
    circuit.addGate(dd::Xmat, 6);
    circuit.addGate(dd::Ymat, 10_pc, 2);
    circuit.addGate(dd::Smat, 22);
    circuit.addGate(dd::Ymat, 22);
    circuit.addGate(dd::Hmat, 22);
    circuit.addGate(dd::Ymat, 21_pc, 20);
    circuit.addGate(dd::Xmat, 28_pc, 6);
    circuit.addGate(dd::Xmat, 15_pc, 7);
    circuit.addGate(dd::Hmat, 22);
    circuit.addGate(dd::Xmat, 7_pc, 16);
    circuit.addGate(dd::Xmat, 12_pc, 3);
    circuit.addGate(dd::Ymat, 6_pc, 15);
    circuit.addGate(dd::Zmat, 29_pc, 20);
    circuit.addGate(dd::Zmat, 11_pc, 27);
    circuit.addGate(dd::Ymat, 25);
    circuit.addGate(dd::Xmat, 2);
    circuit.addGate(dd::Smat, 11);
    circuit.addGate(dd::Zmat, 24);
    circuit.addGate(dd::Ymat, 11_pc, 16);
    circuit.addGate(dd::Xmat, 19);
    circuit.addGate(dd::Xmat, 26_pc, 20);
    circuit.addGate(dd::Ymat, 19_pc, 1);
    circuit.addGate(dd::Ymat, 4_pc, 10);
    circuit.addGate(dd::Ymat, 27);
    circuit.addGate(dd::Ymat, 21);
    circuit.addGate(dd::Ymat, 2);
    circuit.addGate(dd::Zmat, 27_pc, 20);
    circuit.addGate(dd::Xmat, 7_pc, 13);
    circuit.addGate(dd::Xmat, 26_pc, 13);
    circuit.addGate(dd::Smat, 24);
    circuit.addGate(dd::Smat, 18);
    circuit.addGate(dd::Xmat, 22_pc, 23);

    simulateCircuitLIMDDGateByGate(circuit);
}

// Randomly generated circuit on 31 qubis, containing 93 Clifford gates.
TEST(LimTest, generatedCircuit_22) {
    dd::QuantumCircuit circuit(31);

    circuit.addGate(dd::Smat, 29);
    circuit.addGate(dd::Hmat, 15);
    circuit.addGate(dd::Hmat, 13);
    circuit.addGate(dd::Zmat, 22_pc, 16);
    circuit.addGate(dd::Xmat, 25_pc, 1);
    circuit.addGate(dd::Hmat, 0);
    circuit.addGate(dd::Smat, 15);
    circuit.addGate(dd::Zmat, 27_pc, 28);
    circuit.addGate(dd::Ymat, 1_pc, 11);
    circuit.addGate(dd::Zmat, 10_pc, 11);
    circuit.addGate(dd::Zmat, 4_pc, 25);
    circuit.addGate(dd::Zmat, 16);
    circuit.addGate(dd::Zmat, 1_pc, 25);
    circuit.addGate(dd::Ymat, 19);
    circuit.addGate(dd::Xmat, 28_pc, 12);
    circuit.addGate(dd::Ymat, 9);
    circuit.addGate(dd::Zmat, 29);
    circuit.addGate(dd::Ymat, 7_pc, 8);
    circuit.addGate(dd::Xmat, 19_pc, 23);
    circuit.addGate(dd::Smat, 16);
    circuit.addGate(dd::Xmat, 1);
    circuit.addGate(dd::Ymat, 1_pc, 0);
    circuit.addGate(dd::Ymat, 17_pc, 12);
    circuit.addGate(dd::Xmat, 22_pc, 8);
    circuit.addGate(dd::Zmat, 14_pc, 6);
    circuit.addGate(dd::Hmat, 19);
    circuit.addGate(dd::Xmat, 30_pc, 19);
    circuit.addGate(dd::Ymat, 8_pc, 2);
    circuit.addGate(dd::Xmat, 21_pc, 5);
    circuit.addGate(dd::Ymat, 6_pc, 13);
    circuit.addGate(dd::Ymat, 28_pc, 1);
    circuit.addGate(dd::Zmat, 23);
    circuit.addGate(dd::Zmat, 22_pc, 0);
    circuit.addGate(dd::Zmat, 15_pc, 29);
    circuit.addGate(dd::Ymat, 27);
    circuit.addGate(dd::Xmat, 17_pc, 13);
    circuit.addGate(dd::Zmat, 22_pc, 11);
    circuit.addGate(dd::Ymat, 17);
    circuit.addGate(dd::Ymat, 8_pc, 12);
    circuit.addGate(dd::Xmat, 23_pc, 30);
    circuit.addGate(dd::Zmat, 19_pc, 9);
    circuit.addGate(dd::Ymat, 24);
    circuit.addGate(dd::Ymat, 0);
    circuit.addGate(dd::Xmat, 16_pc, 14);
    circuit.addGate(dd::Smat, 4);
    circuit.addGate(dd::Xmat, 28);
    circuit.addGate(dd::Smat, 30);
    circuit.addGate(dd::Xmat, 9);
    circuit.addGate(dd::Ymat, 1_pc, 23);
    circuit.addGate(dd::Ymat, 18);
    circuit.addGate(dd::Hmat, 24);
    circuit.addGate(dd::Ymat, 25_pc, 27);
    circuit.addGate(dd::Zmat, 23_pc, 25);
    circuit.addGate(dd::Ymat, 29_pc, 5);
    circuit.addGate(dd::Zmat, 3_pc, 5);
    circuit.addGate(dd::Smat, 23);
    circuit.addGate(dd::Smat, 23);
    circuit.addGate(dd::Xmat, 15);
    circuit.addGate(dd::Zmat, 2_pc, 18);
    circuit.addGate(dd::Smat, 22);
    circuit.addGate(dd::Zmat, 18_pc, 19);
    circuit.addGate(dd::Xmat, 11);
    circuit.addGate(dd::Xmat, 10_pc, 16);
    circuit.addGate(dd::Hmat, 17);
    circuit.addGate(dd::Xmat, 15);
    circuit.addGate(dd::Xmat, 25);
    circuit.addGate(dd::Zmat, 2_pc, 10);
    circuit.addGate(dd::Ymat, 12_pc, 29);
    circuit.addGate(dd::Zmat, 20_pc, 2);
    circuit.addGate(dd::Xmat, 20_pc, 0);
    circuit.addGate(dd::Zmat, 10);
    circuit.addGate(dd::Ymat, 24_pc, 1);
    circuit.addGate(dd::Ymat, 14);
    circuit.addGate(dd::Ymat, 18_pc, 24);
    circuit.addGate(dd::Ymat, 18);
    circuit.addGate(dd::Zmat, 0);
    circuit.addGate(dd::Xmat, 29_pc, 26);
    circuit.addGate(dd::Ymat, 26);
    circuit.addGate(dd::Xmat, 13_pc, 29);
    circuit.addGate(dd::Ymat, 6);
    circuit.addGate(dd::Xmat, 29_pc, 20);
    circuit.addGate(dd::Zmat, 20);
    circuit.addGate(dd::Zmat, 12_pc, 16);
    circuit.addGate(dd::Zmat, 1_pc, 29);
    circuit.addGate(dd::Smat, 25);
    circuit.addGate(dd::Zmat, 11_pc, 24);
    circuit.addGate(dd::Zmat, 7);
    circuit.addGate(dd::Hmat, 19);
    circuit.addGate(dd::Ymat, 10_pc, 9);
    circuit.addGate(dd::Xmat, 15_pc, 16);
    circuit.addGate(dd::Zmat, 28_pc, 27);
    circuit.addGate(dd::Zmat, 28);
    circuit.addGate(dd::Ymat, 2);

    simulateCircuitLIMDDGateByGate(circuit);
}

